import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { ingestAgencyOffer } from '../dist/partner_ingest.js';
import { projectDomainEvents } from '../dist/ingest.js';
import { leaseAgencyRechecks, completeAgencyRecheck } from '../dist/agency_recheck.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new DB(raw),now='2026-09-15T02:00:00Z';
for(const id of ['a1','a2']){const src=`src-${id}`;raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch) values(?, 'PARTNER_PUSH',?,'PARTNER_CONTRACT','WEBHOOK','SHADOW','MEDIUM','2026-09-15T00:00:00Z',300000,0)").run(src,`${id}.example`);raw.prepare("insert into agency_partner_registry(agency_id,source_id,status,verified_business,terms_snapshot_at) values(?,?,'ENABLED',1,'2026-09-15T00:00:00Z')").run(id,src);}
const offer={agency_offer_id:'ao1',agency_id:'a1',source_id:'src-a1',observation_id:'obs-a1',product_id:'pkg-1',allotment_type:'CLEARANCE',origin:'TPE',destination:'OKA',departure_at:'2026-09-20T08:00:00+08:00',return_at:'2026-09-23T12:00:00+09:00',price:6999,currency:'TWD',tax_inclusion:'INCLUDED',baggage:'20KG',seats_total:2,seats_available:2,inventory_hint:'LIMITED',booking_deadline:'2026-09-16T18:00:00+08:00',ticketing_deadline:'2026-09-16T20:00:00+08:00',refund_change_terms:'NONREFUNDABLE',booking_or_contact_channel:'https://a1.example/book',observed_at:'2026-09-15T00:00:00Z',content_sha256:'a'.repeat(64),canonical_url:'https://a1.example/deal/pkg-1'};
await ingestAgencyOffer(db,offer,'2026-09-15T00:00:01Z');await projectDomainEvents(db,'2026-09-15T00:00:02Z','projector',2);
const none=await leaseAgencyRechecks(db,{agency_id:'a2',worker_id:'w2'},'2026-09-15T01:00:00Z');const leased=await leaseAgencyRechecks(db,{agency_id:'a1',worker_id:'w1'},'2026-09-15T01:00:00Z');
let wrongWorker='';try{await completeAgencyRecheck(db,{recheck_id:'r1',queue_id:leased[0].queue_id,agency_offer_id:'ao1',agency_id:'a1',worker_id:'wrong',readback_basis:'PARTNER_API',source_url:'https://a1.example/api/pkg-1',content_sha256:'b'.repeat(64),observed_at:'2026-09-15T01:00:10Z',price:6888,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00'},'2026-09-15T01:00:11Z')}catch(e){wrongWorker=e.message}
let wrongDomain='';try{await completeAgencyRecheck(db,{recheck_id:'r-domain',queue_id:leased[0].queue_id,agency_offer_id:'ao1',agency_id:'a1',worker_id:'w1',readback_basis:'PARTNER_API',source_url:'https://evil.example/api/pkg-1',content_sha256:'d'.repeat(64),observed_at:'2026-09-15T01:00:10Z',price:6888,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00'},'2026-09-15T01:00:11Z')}catch(e){wrongDomain=e.message}
const ok=await completeAgencyRecheck(db,{recheck_id:'r1',queue_id:leased[0].queue_id,agency_offer_id:'ao1',agency_id:'a1',worker_id:'w1',readback_basis:'PARTNER_API',source_url:'https://a1.example/api/pkg-1',content_sha256:'b'.repeat(64),observed_at:'2026-09-15T01:00:10Z',price:6888,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00'},'2026-09-15T01:00:11Z');
const idem=await completeAgencyRecheck(db,{recheck_id:'r1',queue_id:leased[0].queue_id,agency_offer_id:'ao1',agency_id:'a1',worker_id:'w1',readback_basis:'PARTNER_API',source_url:'https://a1.example/api/pkg-1',content_sha256:'b'.repeat(64),observed_at:'2026-09-15T01:00:10Z',price:6888,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00'},'2026-09-15T01:00:12Z');
const row=raw.prepare("select seller_verification_state,price,seats_available,state from agency_inventory_offers where agency_offer_id='ao1'").get();const q=raw.prepare("select state,claimed_by from candidate_priority_queue where signal_id='ao1'").get();const ev=raw.prepare("select result_state,readback_basis from agency_recheck_evidence where recheck_id='r1'").get();const intent=raw.prepare("select payload_json from candidate_alert_intents where intent_id='agency-provisional:ao1:r1'").get();const payload=JSON.parse(intent.payload_json);
console.log(JSON.stringify({none:none.length,leased:leased.length,wrongWorker,wrongDomain,ok,idem,row,q,ev,payload,intents:raw.prepare("select count(*) n from candidate_alert_intents where intent_id='agency-provisional:ao1:r1'").get().n}));
