import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { ingestPolicyRecord, enrichItineraryPolicy } from '../dist/policy_registry.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values('i1','S00_DIRECT_RT',null,0,'LOW_COMPLEXITY_INCOMPLETE','CONFIRMED','2026-09-15T00:00:00Z')").run();
raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,validating_carrier,segments_json) values('t1','i1','p1','test','ROUND_TRIP','NOT_APPLICABLE_DIRECT','TT',?)").run(JSON.stringify([{origin:'TPE',destination:'KIX',departing_at:'2026-11-02T01:00:00Z',arriving_at:'2026-11-02T03:30:00Z'},{origin:'KIX',destination:'TPE',departing_at:'2026-11-05T08:00:00Z',arriving_at:'2026-11-05T11:00:00Z'}]));
for(const f of ['FARE_VERIFIED','CONNECTION_ACCEPTABLE','BAGGAGE_FEASIBLE','COST_COMPLETE','COUPON_SEQUENCE_CLEAR','DOCUMENT_CLEAR','POLICY_FRESH'])raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values('i1',?,'UNKNOWN','INIT','2026-09-15T00:00:00Z','2026-09-15T00:15:00Z','TEST','init')").run(f);
const hash='c'.repeat(64);
await ingestPolicyRecord(db,{policy_record_id:'jp-entry-v1',policy_code:'JP_ENTRY_TW_VALID_PASSPORT',jurisdiction:'JP',traveler_document_class:'TW_PASSPORT_VALID',observed_at:'2026-09-15T00:00:00Z',effective_from:'2026-01-01T00:00:00Z',effective_to:'2027-01-01T00:00:00Z',jurisdiction_timezone:'Asia/Tokyo',travel_event:'ARRIVAL',source_url:'https://example.go.jp/policy',source_authority:'JP_OFFICIAL',source_snapshot_hash:hash,refresh_margin_hours:24,ttl_hours:72,watch_window_hours:720,decision_status:'CLEAR',status:'CURRENT'},'2026-09-15T00:00:01Z');
const clear=await enrichItineraryPolicy(db,{itinerary_id:'i1',traveler_document_class:'TW_PASSPORT_VALID',requirements:[{document_id:'doc-jp','policy_code':'JP_ENTRY_TW_VALID_PASSPORT',event_selector:'FIRST_ARRIVAL'}]},'2026-09-15T12:00:00Z');
const clearFacets=raw.prepare("select facet_type,status,reason_code,evidence_id from readiness_facets where itinerary_id='i1' and facet_type in ('DOCUMENT_CLEAR','POLICY_FRESH') order by facet_type").all();
const doc=raw.prepare("select jurisdiction,status,valid_for_event_at,authority_source,source_snapshot_id from document_requirements where document_id='doc-jp'").get();
const stale=await enrichItineraryPolicy(db,{itinerary_id:'i1',traveler_document_class:'TW_PASSPORT_VALID',requirements:[{document_id:'doc-jp','policy_code':'JP_ENTRY_TW_VALID_PASSPORT',event_selector:'FIRST_ARRIVAL'}]},'2026-09-20T12:00:00Z');
const staleFacets=raw.prepare("select facet_type,status,reason_code from readiness_facets where itinerary_id='i1' and facet_type in ('DOCUMENT_CLEAR','POLICY_FRESH') order by facet_type").all();
let conflict='NONE'; try{await ingestPolicyRecord(db,{policy_record_id:'jp-entry-v1',policy_code:'JP_ENTRY_TW_VALID_PASSPORT',jurisdiction:'JP',traveler_document_class:'TW_PASSPORT_VALID',observed_at:'2026-09-15T00:00:00Z',jurisdiction_timezone:'Asia/Tokyo',travel_event:'ARRIVAL',source_url:'https://example.go.jp/policy',source_authority:'JP_OFFICIAL',source_snapshot_hash:'d'.repeat(64),refresh_margin_hours:24,ttl_hours:72,decision_status:'CLEAR',status:'CURRENT'});}catch(e){conflict=e.message;}
console.log(JSON.stringify({clear,clearFacets,doc,stale,staleFacets,conflict}));
