import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import { enqueueCandidateSignal, leaseCandidateSignals, ackCandidateSignal } from '../dist/priority.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
await enqueueCandidateSignal(db,{signal_type:'PROMOTION',signal_id:'p1',required_verification:'LIVE_REPRICE',priority_score:60,route_scope:['TPE-KIX'],price_claim:[{currency:'TWD',amount:3999}],source_evidence_id:'obs1',observed_at:'2026-09-15T00:00:00Z'},'2026-09-15T00:00:01Z');
await enqueueCandidateSignal(db,{signal_type:'PROMOTION',signal_id:'p1',required_verification:'LIVE_REPRICE',priority_score:80,route_scope:['TPE-KIX'],price_claim:[{currency:'TWD',amount:3999}],source_evidence_id:'obs2',observed_at:'2026-09-15T00:01:00Z'},'2026-09-15T00:01:01Z');
const first=await leaseCandidateSignals(db,'2026-09-15T00:02:00Z','w1',5,30); const retry=await ackCandidateSignal(db,{queue_id:first[0].queue_id,ok:false,retryable:true,error:'TEMP'},'2026-09-15T00:02:01Z');
const tooEarly=await leaseCandidateSignals(db,'2026-09-15T00:02:10Z','w2',5,30); const later=await leaseCandidateSignals(db,'2026-09-15T00:02:31Z','w2',5,30); const done=await ackCandidateSignal(db,{queue_id:later[0].queue_id,ok:true},'2026-09-15T00:02:32Z');
console.log(JSON.stringify({count:raw.prepare('select count(*) n from candidate_priority_queue').get().n,score:raw.prepare("select priority_score from candidate_priority_queue where signal_id='p1'").get().priority_score,first:first.length,retry,tooEarly:tooEarly.length,later:later.length,done,state:raw.prepare("select state from candidate_priority_queue where signal_id='p1'").get().state}));
