import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import { ingestProviderPricingSnapshot } from '../dist/provider_pricing.js';
import { enqueueProviderSearch } from '../dist/provider_jobs.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}
class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){this.x.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw),now='2026-09-21T00:00:00Z';
raw.prepare("insert into provider_access_registry(provider_id,access_basis,terms_snapshot_at,rate_policy,look_to_book_budget,kill_switch_state,owner,connector_state,supported_verification_json,background_allowed) values('duffel','OFFICIAL_API','2026-09-15T00:00:00Z','TARGETED_ONLY',2,'CLEAR','provider','IMPLEMENTED','[\"LIVE_REPRICE\"]',1)").run();
const snap={pricing_snapshot_id:'duffel-pricing-1',provider_id:'duffel',usage_window_kind:'CALENDAR_MONTH',search_to_book_threshold:2,hard_search_cap:2,currency:'USD',rate_json:{excess_search_fee:'provider-evidence-only'},source_url:'https://duffel.com/pricing',raw_sha256:'a'.repeat(64),observed_at:'2026-09-20T00:00:00Z',effective_from:'2026-09-20T00:00:00Z',expires_at:'2026-10-20T00:00:00Z'};
const ing=await ingestProviderPricingSnapshot(db,snap,now);const idem=await ingestProviderPricingSnapshot(db,snap,now);let conflict=false;try{await ingestProviderPricingSnapshot(db,{...snap,hard_search_cap:3},now)}catch(e){conflict=String(e).includes('IMMUTABLE_CONFLICT')}
const q=n=>({slices:[{origin:'TPE',destination:'KIX',departure_date:`2026-11-${String(n).padStart(2,'0')}`}],passengers:[{type:'adult'}]});
const one=await enqueueProviderSearch(db,{provider_id:'duffel',mode:'BACKGROUND',query:q(1)},now);const oneReplay=await enqueueProviderSearch(db,{provider_id:'duffel',mode:'BACKGROUND',query:q(1)},now);const two=await enqueueProviderSearch(db,{provider_id:'duffel',mode:'BACKGROUND',query:q(2)},now);let thirdError='';try{await enqueueProviderSearch(db,{provider_id:'duffel',mode:'BACKGROUND',query:q(3)},now)}catch(e){thirdError=e.message}
const usage=raw.prepare("select search_count,confirmed_order_count,circuit_state,opened_reason from provider_usage_windows where provider_id='duffel'").get();
raw.prepare("update provider_pricing_snapshots set expires_at='2026-09-20T23:59:59Z' where pricing_snapshot_id='duffel-pricing-1'").run();let staleError='';try{raw.prepare("update provider_usage_windows set circuit_state='CLEAR',search_count=0 where provider_id='duffel'").run();await enqueueProviderSearch(db,{provider_id:'duffel',mode:'USER_REQUEST',query:q(4)},now)}catch(e){staleError=e.message}
console.log(JSON.stringify({ing,idem,conflict,one,oneReplay,two,thirdError,usage,staleError,jobs:raw.prepare("select count(*) n from verification_jobs where provider_id='duffel'").get().n}));
