import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { applySourceOnboardingReview, disableSource } from '../dist/source_onboarding.js';
import { scheduleDueSources } from '../dist/scheduler.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); raw.exec(fs.readFileSync(new URL('../generated/seed.generated.sql',import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare("insert into audit_evidence(evidence_id,gate_id,spec_version,test_report_hash,provider_readback,unresolved_items,created_at) values('ev-shadow','PG25','1.3',?,'{}','[]','2026-09-15T00:00:00Z')").run('a'.repeat(64));
raw.prepare("insert into audit_evidence(evidence_id,gate_id,spec_version,test_report_hash,provider_readback,unresolved_items,created_at) values('ev-enable','PG31','1.3',?,'{}','[]','2026-09-15T00:10:00Z')").run('b'.repeat(64));
let directEnableBlocked=false; try{await applySourceOnboardingReview(db,{review_id:'bad-direct',source_id:'jejuair_events',target_state:'ENABLED',terms_snapshot_at:'2026-09-15T00:00:00Z',evidence_id:'ev-enable',access_basis_valid:true,privacy_review_pass:true,parser_contract_pass:true,provenance_hash_pass:true,rate_budget_pass:true,shadow_pass:true},'2026-09-15T00:00:01Z')}catch(e){directEnableBlocked=String(e).includes('SOURCE_MUST_PASS_SHADOW_FIRST')}
const before=await scheduleDueSources(db,'2026-09-15T00:01:00Z',50);
const shadow=await applySourceOnboardingReview(db,{review_id:'r-shadow',source_id:'trinity_airways_official',target_state:'SHADOW',terms_snapshot_at:'2026-09-15T00:01:00Z',evidence_id:'ev-shadow',access_basis_valid:true,privacy_review_pass:true,parser_contract_pass:true},'2026-09-15T00:01:01Z');
const afterShadow=await scheduleDueSources(db,'2026-09-15T00:02:00Z',50);
let incompleteEnableBlocked=false; try{await applySourceOnboardingReview(db,{review_id:'bad-enable',source_id:'trinity_airways_official',target_state:'ENABLED',terms_snapshot_at:'2026-09-15T00:10:00Z',evidence_id:'ev-enable',access_basis_valid:true,privacy_review_pass:true,parser_contract_pass:true,provenance_hash_pass:true,rate_budget_pass:true,shadow_pass:false},'2026-09-15T00:10:01Z')}catch(e){incompleteEnableBlocked=String(e).includes('SOURCE_ENABLE_GATES_INCOMPLETE')}
const enabled=await applySourceOnboardingReview(db,{review_id:'r-enable',source_id:'trinity_airways_official',target_state:'ENABLED',terms_snapshot_at:'2026-09-15T00:10:00Z',evidence_id:'ev-enable',access_basis_valid:true,privacy_review_pass:true,parser_contract_pass:true,provenance_hash_pass:true,rate_budget_pass:true,shadow_pass:true},'2026-09-15T00:10:02Z');
const idem=await applySourceOnboardingReview(db,{review_id:'r-enable',source_id:'trinity_airways_official',target_state:'ENABLED',terms_snapshot_at:'2026-09-15T00:10:00Z',evidence_id:'ev-enable',access_basis_valid:true,privacy_review_pass:true,parser_contract_pass:true,provenance_hash_pass:true,rate_budget_pass:true,shadow_pass:true},'2026-09-15T00:10:03Z');
const disabled=await disableSource(db,{source_id:'trinity_airways_official',reason:'terms revoked'},'2026-09-15T00:20:00Z');
console.log(JSON.stringify({directEnableBlocked,before,shadow,afterShadow,incompleteEnableBlocked,enabled,idem,disabled,source:raw.prepare("select lifecycle_state,status,kill_switch,kill_switch_state,terms_snapshot_at from source_registry where source_id='trinity_airways_official'").get(),reviews:raw.prepare("select count(*) n from source_onboarding_reviews where source_id='trinity_airways_official'").get().n,jobs:raw.prepare("select count(*) n from verification_jobs where source_id='trinity_airways_official'").get().n}));
