import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { ingestOfferSnapshot } from '../dist/offers.js'; import { upsertPaymentProfile, ingestPricingQuote } from '../dist/checkout_pricing.js'; import { projectDomainEvents } from '../dist/ingest.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of stmts)out.push(await s.run());this.db.exec('COMMIT');return out}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));raw.exec(fs.readFileSync(new URL('../generated/seed.generated.sql',import.meta.url),'utf8'));const db=new DB(raw);
raw.prepare("update provider_access_registry set terms_snapshot_at='2026-09-15T00:00:00Z' where provider_id='duffel'").run();
const structure={slices:[{segments:[{segment_id:'s1',origin:'TPE',destination:'KIX',departing_at:'2026-11-03T01:00:00Z',arriving_at:'2026-11-03T03:00:00Z',passengers:[]}]}],available_services:[],price_scope:'FLIGHT_TOTAL_INCLUDES_TAX_EXCLUDES_SERVICES'};
await ingestOfferSnapshot(db,{provider_offer_id:'offp',query_fingerprint:'q1',provider:'duffel',currency:'TWD',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-09-15T01:00:00Z',raw_sha256:'c'.repeat(64),offer_total:5000,fare_freshness:'REFRESHED_LIVE',cached_or_live:'LIVE',offer_structure:structure});
raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values('i1','S01_DIRECT_OW',NULL,0,'LOW','CONFIRMED','2026-09-15T00:00:00Z')").run();
raw.prepare("insert into cost_components(cost_id,itinerary_id,type,amount,currency,twd_amount,inclusion_state,source_offer_id,dedupe_key,certainty,paid_state,refundable,observed_at) values('c1','i1','OFFER_TOTAL',5000,'TWD',5000,'INCLUDED_IN_OFFER','offp','offer-total','CONFIRMED','UNPAID',0,'2026-09-15T00:00:00Z')").run();
raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values('i1','COST_COMPLETE','FAIL','MANDATORY_EXTRAS_NOT_PROVEN','2026-09-15T00:00:00Z','2026-09-15T00:15:00Z','SYSTEM','offer:offp')").run();
await upsertPaymentProfile(db,{payment_profile_id:'payp',provider_id:'duffel',payment_method_class:'CARD',credential_binding:'DUFFEL_PAYMENT_CARD_ID',enabled:true,expires_at:'2026-09-15T00:20:00Z'},'2026-09-15T00:01:00Z');
await ingestPricingQuote(db,{quote_id:'qp',provider_offer_id:'offp',provider_id:'duffel',payment_profile_id:'payp',selected_services:[],payment_method_class:'CARD',currency:'TWD',fare_and_services_total:5000,surcharge_total:100,grand_total:5100,priced_at:'2026-09-15T00:02:00Z',expires_at:'2026-09-15T00:20:00Z',raw_sha256:'d'.repeat(64),price_scope:'CHECKOUT_TOTAL_WITH_SELECTED_SERVICES_AND_PAYMENT_SURCHARGE'});
const projected=await projectDomainEvents(db,'2026-09-15T00:02:01Z','test',2);
console.log(JSON.stringify({projected,cost:raw.prepare("select type,amount,twd_amount,certainty,pricing_quote_id from cost_components where cost_id='c1'").get(),facet:raw.prepare("select status,reason_code,authority,evidence_id from readiness_facets where itinerary_id='i1' and facet_type='COST_COMPLETE'").get(),event:raw.prepare("select state from domain_outbox where event_type='PRICING_QUOTE' and entity_id='qp'").get()}));
