import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import worker from '../dist/worker.js'; import { installKey, authEnv, signedRequest } from './scoped_auth_helper.mjs';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){const o=[];this.x.exec('BEGIN');try{for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);const secret='test-secret-0123456789';installKey(raw,{allowedPaths:['/candidate/evaluate']});const env=authEnv(db,secret);
function itin(id,state='CONFIRMED',fresh=true,cost=1,amount=5000){raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values(?, 'S00_DIRECT_RT',?,?,'LOW',?,'2026-09-15T00:00:00Z')").run(id,amount,cost,state);for(const t of ['FARE_VERIFIED','DOCUMENT_CLEAR','CONNECTION_ACCEPTABLE','BAGGAGE_FEASIBLE','COST_COMPLETE','COUPON_SEQUENCE_CLEAR','POLICY_FRESH'])raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values(?,?,'PASS','OK','2026-09-15T00:00:00Z',?,'TEST','e')").run(id,t,fresh?'2099-01-01T00:00:00Z':'2000-01-01T00:00:00Z');raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,segments_json) values(?,?,?,'provider-a','ROUND_TRIP','THROUGH_TICKET_CARRIER_PROTECTED','[{\"from\":\"TPE\",\"to\":\"KIX\"}]')").run(`t-${id}`,id,`p-${id}`);}
itin('good','CONFIRMED',true,1,9900);itin('stale','CONFIRMED',false);itin('prob','PROBABLE',true);itin('nocost','CONFIRMED',true,0);
async function post(obj){const body=JSON.stringify(obj);const req=await signedRequest('https://x/candidate/evaluate',body,{secret});const r=await worker.fetch(req,env);return {status:r.status,body:await r.json()};}
const good=await post({itinerary_id:'good'});const stale=await post({itinerary_id:'stale'});const prob=await post({itinerary_id:'prob'});const nocost=await post({itinerary_id:'nocost'});const forged=await post({itinerary_id:'prob',actionable:true});const forgedPayload=await post({itinerary_id:'good',payload:{cash_trip_cost_twd:1},intent_id:'x'});const provisional=await post({itinerary_id:'prob',provisional_trigger:true});const admin=await post({itinerary_id:'good',alert_class:'ADMIN'});
const rows=raw.prepare("select intent_id,payload_json from candidate_alert_intents order by intent_id").all().map(r=>({intent_id:r.intent_id,payload:JSON.parse(r.payload_json)}));
console.log(JSON.stringify({good,stale,prob,nocost,forged,forgedPayload,provisional,admin,rows}));
