import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { ingestCarrierTicketingPolicy, evaluateTicketingGuards } from '../dist/ticketing_guard.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){this.x.exec('BEGIN');try{const o=[];for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);
function itin(id){raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values(?, 'S15_NESTED',NULL,0,'HIGH','PROBABLE','2026-09-15T00:00:00Z')").run(id)}
function ticket(id,it,times,skip=false){raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,validating_carrier,segments_json) values(?,?,?,'CI','ROUND_TRIP','THROUGH_TICKET_CARRIER_PROTECTED','CI',?)").run(id,it,id,JSON.stringify(times.map((x,i)=>({departing_at:x[0],arriving_at:x[1],intentionally_skipped:skip&&i===0}))))}
itin('skip');ticket('ts','skip',[['2027-01-01T00:00:00Z','2027-01-01T03:00:00Z'],['2027-01-10T00:00:00Z','2027-01-10T03:00:00Z']],true);const missingPolicy=await evaluateTicketingGuards(db,'skip','2026-09-15T00:00:00Z');await ingestCarrierTicketingPolicy(db,{policy_id:'ci-seq',carrier:'CI',policy_type:'COUPON_SEQUENCE',consequence:'COUPON_RECALCULATION_LIABILITY',terms_url:'https://example.test/ci',article_or_clause:'sequence',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-10-15T00:00:00Z',source_snapshot_hash:'a'.repeat(64),status:'CURRENT'},'2026-09-15T00:00:00Z');const withPolicy=await evaluateTicketingGuards(db,'skip','2026-09-15T00:01:00Z');
itin('nested');ticket('ta','nested',[['2027-01-01T00:00:00Z','2027-01-01T03:00:00Z'],['2027-01-10T00:00:00Z','2027-01-10T03:00:00Z']]);ticket('tb','nested',[['2027-01-05T00:00:00Z','2027-01-05T03:00:00Z'],['2027-01-08T00:00:00Z','2027-01-08T03:00:00Z']]);const nestedUnknown=await evaluateTicketingGuards(db,'nested','2026-09-15T00:02:00Z');await ingestCarrierTicketingPolicy(db,{policy_id:'ci-b2b',carrier:'CI',policy_type:'BACK_TO_BACK',consequence:'ALLOW',terms_url:'https://example.test/ci-b2b',article_or_clause:'allowed synthetic',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-10-15T00:00:00Z',source_snapshot_hash:'b'.repeat(64),status:'CURRENT'},'2026-09-15T00:00:00Z');raw.prepare("update itinerary_candidates set verification_state='PROBABLE' where itinerary_id='nested'").run();const nestedAllowed=await evaluateTicketingGuards(db,'nested','2026-09-15T00:03:00Z');
console.log(JSON.stringify({missingPolicy,withPolicy,nestedUnknown,nestedAllowed,skipFacet:raw.prepare("select status,reason_code from readiness_facets where itinerary_id='skip' and facet_type='COUPON_SEQUENCE_CLEAR'").get(),nestedState:raw.prepare("select verification_state from itinerary_candidates where itinerary_id='nested'").get()}));
