import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { upsertRuntimeProfile, baggageQueryFromProfile } from '../dist/profile.js';
import { upsertSearchCampaign, planSearchesForQueue } from '../dist/search_planner.js';
import { enqueueCandidateSignal } from '../dist/priority.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of stmts)out.push(await s.run());this.db.exec('COMMIT');return out}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare("insert into provider_access_registry(provider_id,access_basis,terms_snapshot_at,rate_policy,kill_switch_state,owner,connector_state,supported_verification_json,background_allowed) values('p','OFFICIAL_API','2026-09-15T00:00:00Z','TARGETED_ONLY','CLEAR','test','IMPLEMENTED','[\"LIVE_REPRICE\"]',1)").run();
const profile={profile_id:'synthetic-return',home_city:'Synthetic',home_airports:['TPE','TSA'],checked_bag_pattern:'RETURN_ONLY',baggage_kg:20,seat_required:false,red_eye_ok:true,self_transfer_ok:true,overnight_transfer_ok:false,airport_change_ok:false,mainland_permit_status:'UNKNOWN',korea_entry_profile:'CHECK_AT_QUERY_TIME',foreign_origin_ok:true,positioning_cost_attribution:'FULL',max_positioning_cost_twd:2500,value_of_time_twd_per_hour:300,min_savings_for_self_transfer_twd:2500,currency:'TWD'};
await upsertRuntimeProfile(db,profile,'2026-09-15T00:00:00Z');
raw.prepare("insert into promotion_events(event_id,fingerprint,state,market,routes_json,observed_at,updated_at,travel_window) values('promo-prof','fp-prof','DISCOVERED','TW','[\"TPE-KIX\"]','2026-09-15T00:00:00Z','2026-09-15T00:00:00Z','{\"start\":\"2026-11-01\",\"end\":\"2026-11-10\"}')").run();
await enqueueCandidateSignal(db,{signal_type:'PROMOTION',signal_id:'promo-prof',required_verification:'LIVE_REPRICE',priority_score:70,route_scope:['TPE-KIX'],source_evidence_id:'obs-prof',observed_at:'2026-09-15T00:00:00Z'},'2026-09-15T00:00:00Z');
await upsertSearchCampaign(db,{campaign_id:'camp-prof',profile_id:'synthetic-return',provider_id:'p',origin_airports:['TPE'],destination_airports:['KIX'],departure_dates:['2026-11-02'],trip_lengths_nights:[3],passengers:[{type:'adult'}],max_queries_per_signal:2,enabled:true,expires_at:'2026-12-31T00:00:00Z'},'2026-09-15T00:00:00Z');
await planSearchesForQueue(db,'camp-prof','promotion:promo-prof','2026-09-15T00:01:00Z');
const query=JSON.parse(raw.prepare("select query_json from provider_search_plans").get().query_json);
let missing='NONE'; try{await upsertSearchCampaign(db,{campaign_id:'bad',profile_id:'missing',provider_id:'p',origin_airports:['TPE'],destination_airports:['KIX'],departure_dates:['2026-11-02'],trip_lengths_nights:[3],passengers:[{type:'adult'}],expires_at:'2026-12-31T00:00:00Z'},'2026-09-15T00:00:00Z')}catch(e){missing=e.message}
console.log(JSON.stringify({stored:raw.prepare("select profile_id,checked_bag_pattern,baggage_kg,seat_required from runtime_profiles where profile_id='synthetic-return'").get(),query,oneway:baggageQueryFromProfile(profile,1),roundtrip:baggageQueryFromProfile(profile,2),missing}));
