import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { enqueueCandidateSignal } from '../dist/priority.js';
import { ingestOfferSnapshot } from '../dist/offers.js';
import { completeProviderJob } from '../dist/provider_jobs.js';
import { actionable } from '../dist/core.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new DB(raw);
raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch) values('src1','OFFICIAL_PROMOTION','airline.test','PUBLIC_OFFICIAL_PAGE','WEBHOOK','SHADOW','HIGH','2026-09-15T00:00:00Z',300000,0)").run();
raw.prepare("insert into source_observations(observation_id,source_id,observed_at,canonical_url,content_sha256,parser_version,access_basis,privacy_class,access_basis_snapshot,retention_until,content_version) values('obs-direct','src1','2026-09-15T00:00:00Z','https://airline.test/promo',?,'test','PUBLIC_OFFICIAL_PAGE','PUBLIC','PUBLIC_OFFICIAL_PAGE','2026-12-15T00:00:00Z',1)").run('a'.repeat(64));
raw.prepare("insert into provider_access_registry(provider_id,access_basis,terms_snapshot_at,rate_policy,look_to_book_budget,kill_switch_state,owner,connector_state,supported_verification_json,credential_binding,background_allowed) values('airline:test','OFFICIAL_API','2026-09-15T00:00:00Z','TARGETED_ONLY',1000,'CLEAR','airline','IMPLEMENTED','[\"LIVE_REPRICE\"]','TEST_TOKEN',1)").run();
await enqueueCandidateSignal(db,{signal_type:'PROMOTION',signal_id:'promo-direct',required_verification:'LIVE_REPRICE',priority_score:90,route_scope:['TPE-KIX'],source_evidence_id:'obs-direct',observed_at:'2026-09-15T00:00:00Z'},'2026-09-15T00:00:00Z');
const queueId='promotion:promo-direct',qfp='direct-qfp';
raw.prepare("insert into search_campaigns(campaign_id,profile_id,provider_id,origin_airports_json,destination_airports_json,departure_dates_json,trip_lengths_json,passengers_json,max_queries_per_signal,enabled,expires_at,created_at,updated_at) values('c-direct','synthetic','airline:test','[\"TPE\"]','[\"KIX\"]','[\"2026-11-02\"]','[3]','[{\"type\":\"adult\"}]',1,1,'2026-12-31T00:00:00Z','2026-09-15T00:00:00Z','2026-09-15T00:00:00Z')").run();
raw.prepare("insert into verification_jobs(job_id,job_type,target_class,payload_json,state,attempts,available_at,created_at,provider_id,query_fingerprint,provider_mode) values('job-direct','LIVE_REPRICE','PROVIDER_API','{}','LEASED',1,'2026-09-15T00:00:00Z','2026-09-15T00:00:00Z','airline:test',?,'USER_REQUEST')").run(qfp);
raw.prepare("insert into provider_search_plans(plan_id,campaign_id,queue_id,provider_id,query_fingerprint,query_json,state,provider_job_id,attempts,next_attempt_at,created_at,updated_at) values('plan-direct','c-direct',?,'airline:test',?,'{}','DISPATCHED','job-direct',1,'2026-09-15T00:00:00Z','2026-09-15T00:00:00Z','2026-09-15T00:00:00Z')").run(queueId,qfp);
raw.prepare("insert into provider_job_consumers(job_id,plan_id,queue_id,created_at) values('job-direct','plan-direct',?,'2026-09-15T00:00:00Z')").run(queueId);
const structure={slices:[{segments:[{origin:'TPE',destination:'KIX',departing_at:'2026-11-02T01:00:00Z',arriving_at:'2026-11-02T03:30:00Z',marketing_carrier:'TT',operating_carrier:'TT',flight_number:'101'}]},{segments:[{origin:'KIX',destination:'TPE',departing_at:'2026-11-05T08:00:00Z',arriving_at:'2026-11-05T11:00:00Z',marketing_carrier:'TT',operating_carrier:'TT',flight_number:'102'}]}]};
await ingestOfferSnapshot(db,{provider_offer_id:'offer-direct',query_fingerprint:qfp,provider:'airline:test',currency:'TWD',observed_at:'2026-09-15T00:01:00Z',expires_at:'2026-09-15T02:00:00Z',raw_sha256:'b'.repeat(64),source_snapshot_id:'job-direct',offer_total:4999,fare_freshness:'LIVE',cached_or_live:'LIVE',offer_structure:structure});
const result=await completeProviderJob(db,{job_id:'job-direct',provider_id:'airline:test',success:true},'2026-09-15T00:02:00Z');
const itin=raw.prepare("select itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,verification_state from itinerary_candidates").get();
const ticket=raw.prepare("select ticket_type,connection_protection_type,validating_carrier,segments_json from ticket_components").get();
const facets=raw.prepare("select facet_type,status,reason_code,expires_at,authority,evidence_id from readiness_facets order by facet_type").all();
const cost=raw.prepare("select amount,currency,twd_amount,inclusion_state,source_offer_id from cost_components").get();
const isActionable=actionable(itin.verification_state,facets,new Date('2026-09-15T00:03:00Z'));
const attributionIntent=raw.prepare("select event_type,state from domain_outbox where event_type='CONFIRMED_CANDIDATE'").get();
console.log(JSON.stringify({result,itin,ticket:{...ticket,segments:JSON.parse(ticket.segments_json)},facets,cost,isActionable,attributionIntent}));
