import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import worker from '../dist/worker.js';
import { installKey, authEnv, signedRequest } from './scoped_auth_helper.mjs';

class Stmt{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}
class DB{constructor(x){this.x=x}prepare(q){return new Stmt(this.x.prepare(q))}async batch(a){const o=[];this.x.exec('BEGIN IMMEDIATE');try{for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
async function call(env,keyId,secret,path,payload){const body=JSON.stringify(payload);const r=await worker.fetch(await signedRequest(`https://fare.example${path}`,body,{keyId,secret}),env);let data=null;try{data=await r.json()}catch{}return{status:r.status,data};}
const root=new URL('../',import.meta.url);const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));raw.exec(fs.readFileSync(new URL('../generated/seed.generated.sql',import.meta.url),'utf8'));const db=new DB(raw);
const secret='shadow-review-secret-0123456789';const commit='d'.repeat(40);const paths=['/shadow/reviews','/shadow/reviews/readback','/shadow/acceptance/readback'];
installKey(raw,{keyId:'wrong-shadow-role',role:'TEST',allowedPaths:paths});installKey(raw,{keyId:'shadow-reviewer',role:'SHADOW_REVIEWER',allowedPaths:paths});
const env={...authEnv(db,secret),FARE_COMMIT_SHA:commit,FARE_DEPLOYMENT_MODE:'SHADOW_ACCEPTANCE'};
const sourceId=raw.prepare("SELECT source_id FROM source_registry ORDER BY source_id LIMIT 1").get().source_id;
const agencyId='shadow-agency';raw.prepare("INSERT INTO agency_partner_registry(agency_id,status,verified_business) VALUES(?,'ACTIVE',1)").run(agencyId);
function obs(id,at){raw.prepare("INSERT INTO source_observations(observation_id,source_id,observed_at,content_sha256,access_basis,privacy_class) VALUES(?,?,?,?,?,?)").run(id,sourceId,at,('a'+id).padEnd(64,'0').slice(0,64),'PUBLIC','PUBLIC');}
obs('obs-source','2026-09-16T00:00:00Z');obs('obs-promo','2026-09-16T00:01:00Z');obs('obs-agency','2026-09-16T00:02:00Z');obs('obs-email','2026-09-16T00:03:00Z');obs('obs-route','2026-09-16T00:04:00Z');
raw.prepare("INSERT INTO itinerary_candidates(itinerary_id,strategy_type,cost_complete,risk_class,verification_state,updated_at) VALUES('itin-1','S09',1,'LOW','CONFIRMED','2026-09-16T00:00:00Z')").run();raw.prepare("INSERT INTO candidate_plan_intakes(intake_id,itinerary_id,payload_sha256,observed_at) VALUES('intake-1','itin-1',?,'2026-09-16T00:00:00Z')").run('b'.repeat(64));
raw.prepare("INSERT INTO promotion_events(event_id,fingerprint,state,routes_json,observed_at,updated_at) VALUES('promo-1','fp-1','DISCOVERED','[]','2026-09-16T00:01:00Z','2026-09-16T00:01:00Z')").run();raw.prepare("INSERT INTO promotion_event_evidence(event_id,observation_id) VALUES('promo-1','obs-promo')").run();
raw.prepare("INSERT INTO agency_inventory_offers(agency_offer_id,agency_id,seller_verification_state,product_id,allotment_type,origin,destination,departure_at,price,currency,tax_inclusion,booking_or_contact_channel,observed_at,source_evidence_id,state) VALUES('agency-offer-1',?,'VERIFIED','prod','ALLOTMENT','TPE','NRT','2026-10-01T00:00:00Z',1000,'TWD','INCLUDED','WEB','2026-09-16T00:02:00Z','obs-agency','ACTIVE')").run(agencyId);
raw.prepare("INSERT INTO email_evidence(message_id,source_id,observation_id,from_address,from_domain,received_at,subject,body_sha256,attachment_sha256_json,dkim_result,spf_result,dmarc_result,canonical_links_json,expanded_links_json,link_risk_class,trust_class,retention_until) VALUES('msg-1',?,'obs-email','a@example.com','example.com','2026-09-16T00:03:00Z','s',?,'[]','PASS','PASS','PASS','[]','[]','LOW','TRUSTED','2026-10-16T00:03:00Z')").run(sourceId,'c'.repeat(64));
raw.prepare("INSERT INTO route_universe_entries(route_id,origin_airport,destination_airport,service_type,first_seen_at,last_seen_at,status,official_evidence_id) VALUES('route-1','TPE','NRT','DIRECT','2026-09-16T00:04:00Z','2026-09-16T00:04:00Z','ACTIVE','obs-route')").run();

const base=(x)=>({sample_id:x.sample_id,subject_id:x.subject_id,subject_type:x.subject_type,observed_at:x.observed_at,label:x.label??'TRUE_DEAL',complex:x.complex??false,source_discovery:x.source_discovery??false,agency_clearance:x.agency_clearance??false,false_actionable:x.false_actionable??false,safety_error_code:x.safety_error_code??null,evidence_id:x.evidence_id});
const itinerary=base({sample_id:'s-itin',subject_id:'itin-1',subject_type:'ITINERARY',observed_at:'2026-09-16T00:00:00Z',complex:true,evidence_id:'intake-1'});
const wrongRole=await call(env,'wrong-shadow-role',secret,'/shadow/reviews',itinerary);
const missingCommit=await call({...authEnv(db,secret),FARE_DEPLOYMENT_MODE:'SHADOW_ACCEPTANCE'},'shadow-reviewer',secret,'/shadow/reviews',itinerary);
const prodWrite=await call({...env,FARE_DEPLOYMENT_MODE:'PRODUCTION'},'shadow-reviewer',secret,'/shadow/reviews',itinerary);
const complexMismatch=await call(env,'shadow-reviewer',secret,'/shadow/reviews',{...itinerary,complex:false,sample_id:'s-complex-bad'});
const observedMismatch=await call(env,'shadow-reviewer',secret,'/shadow/reviews',{...itinerary,observed_at:'2026-09-15T00:00:00Z',sample_id:'s-time-bad'});
const itineraryWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',itinerary);const itineraryReplay=await call(env,'shadow-reviewer',secret,'/shadow/reviews',itinerary);const itineraryRead=await call(env,'shadow-reviewer',secret,'/shadow/reviews/readback',{sample_id:'s-itin'});
const changedSameSample=await call(env,'shadow-reviewer',secret,'/shadow/reviews',{...itinerary,label:'NORMAL'});const duplicateUnit=await call(env,'shadow-reviewer',secret,'/shadow/reviews',{...itinerary,sample_id:'s-itin-2'});
const canonicalMismatch=await call(env,'shadow-reviewer',secret,'/shadow/reviews',{...itinerary,sample_id:'s-bad-evidence',evidence_id:'missing'});
const promoWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',base({sample_id:'s-promo',subject_id:'promo-1',subject_type:'PROMOTION',observed_at:'2026-09-16T00:01:00Z',label:'PROMO_NOT_BOOKABLE',evidence_id:'obs-promo'}));
const agencyWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',base({sample_id:'s-agency',subject_id:'agency-offer-1',subject_type:'AGENCY_OFFER',observed_at:'2026-09-16T00:02:00Z',label:'AGENCY_CLEARANCE_TRUE',agency_clearance:true,evidence_id:'obs-agency'}));
const sourceWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',base({sample_id:'s-source',subject_id:'obs-source',subject_type:'SOURCE_EVENT',observed_at:'2026-09-16T00:00:00Z',label:'SOURCE_FIRST_WIN',source_discovery:true,evidence_id:'obs-source'}));
const emailWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',base({sample_id:'s-email',subject_id:'msg-1',subject_type:'EMAIL',observed_at:'2026-09-16T00:03:00Z',label:'EMAIL_AUTH_FAIL',evidence_id:'obs-email'}));
const routeWrite=await call(env,'shadow-reviewer',secret,'/shadow/reviews',base({sample_id:'s-route',subject_id:'route-1',subject_type:'ROUTE',observed_at:'2026-09-16T00:04:00Z',label:'ROUTE_UNIVERSE_NEW_SIGNAL',source_discovery:true,evidence_id:'obs-route'}));
await worker.scheduled({scheduledTime:Date.parse('2026-09-16T00:01:00Z')},env);await worker.scheduled({scheduledTime:Date.parse('2026-09-16T00:02:00Z')},env);await worker.scheduled({scheduledTime:Date.parse('2026-09-17T00:01:00Z')},{...env,FARE_DEPLOYMENT_MODE:'PRODUCTION'});
const runtimeDaysAfterScheduler=raw.prepare("SELECT count(*) n FROM shadow_runtime_days WHERE commit_sha=?").get(commit).n;
const initialAcceptance=await call(env,'shadow-reviewer',secret,'/shadow/acceptance/readback',{});

for(let d=1;d<=14;d++){const day=`2026-09-${String(d).padStart(2,'0')}`;raw.prepare("INSERT OR IGNORE INTO shadow_runtime_days(commit_sha,runtime_date,deployment_mode,observed_at) VALUES(?,?,'SHADOW_ACCEPTANCE',?)").run(commit,day,`${day}T00:01:00Z`);}
for(let i=0;i<150;i++){const complex=i<30;const strategies=['S09','S11','S12','S14','S15'];const strategy=complex?strategies[i%5]:null;raw.prepare("INSERT INTO shadow_review_samples(sample_id,subject_type,subject_id,evidence_id,observed_at,label,complex,source_discovery,agency_clearance,false_actionable,safety_error_code,strategy_type,reviewer_key_id,review_payload_sha256,commit_sha,created_at) VALUES(?,?,?,?,?,'TRUE_DEAL',?,0,0,0,NULL,?,'shadow-reviewer',?,?,'2026-09-16T01:00:00Z')").run(`bulk-it-${i}`,'ITINERARY',`bulk-it-${i}`,`bulk-ev-${i}`,'2026-09-16T01:00:00Z',complex?1:0,strategy,'e'.repeat(64),commit);}
for(let i=0;i<30;i++)raw.prepare("INSERT INTO shadow_review_samples(sample_id,subject_type,subject_id,evidence_id,observed_at,label,complex,source_discovery,agency_clearance,false_actionable,safety_error_code,strategy_type,reviewer_key_id,review_payload_sha256,commit_sha,created_at) VALUES(?,?,?,?,?,'SOURCE_FIRST_WIN',0,1,0,0,NULL,NULL,'shadow-reviewer',?,?,'2026-09-16T01:00:00Z')").run(`bulk-src-${i}`,'SOURCE_EVENT',`bulk-src-${i}`,`bulk-src-${i}`,'2026-09-16T01:00:00Z','f'.repeat(64),commit);
for(let i=0;i<10;i++)raw.prepare("INSERT INTO shadow_review_samples(sample_id,subject_type,subject_id,evidence_id,observed_at,label,complex,source_discovery,agency_clearance,false_actionable,safety_error_code,strategy_type,reviewer_key_id,review_payload_sha256,commit_sha,created_at) VALUES(?,?,?,?,?,'AGENCY_CLEARANCE_TRUE',0,0,1,0,NULL,NULL,'shadow-reviewer',?,?,'2026-09-16T01:00:00Z')").run(`bulk-ag-${i}`,'AGENCY_OFFER',`bulk-ag-${i}`,`bulk-ag-ev-${i}`,'2026-09-16T01:00:00Z','1'.repeat(64),commit);
const fullAcceptance=await call(env,'shadow-reviewer',secret,'/shadow/acceptance/readback',{});const differentCommitAcceptance=await call({...env,FARE_COMMIT_SHA:'e'.repeat(40)},'shadow-reviewer',secret,'/shadow/acceptance/readback',{});const productionAcceptance=await call({...env,FARE_DEPLOYMENT_MODE:'PRODUCTION'},'shadow-reviewer',secret,'/shadow/acceptance/readback',{});
console.log(JSON.stringify({wrong_role:wrongRole.status,missing_commit:missingCommit.status,production_write:prodWrite.status,complex_mismatch:complexMismatch.status,observed_mismatch:observedMismatch.status,itinerary_write:itineraryWrite.status,itinerary_replay:itineraryReplay.status,read_reviewer:itineraryRead.data?.review?.reviewer_key_id,read_commit:itineraryRead.data?.review?.commit_sha,changed_same_sample:changedSameSample.status,duplicate_unit:duplicateUnit.status,canonical_mismatch:canonicalMismatch.status,promo:promoWrite.status,agency:agencyWrite.status,source:sourceWrite.status,email:emailWrite.status,route:routeWrite.status,runtime_days_after_scheduler:runtimeDaysAfterScheduler,initial_pass:initialAcceptance.data?.pass,full_pass:fullAcceptance.data?.pass,full_days:fullAcceptance.data?.shadow_days,full_candidates:fullAcceptance.data?.labeled_candidates,full_complex:fullAcceptance.data?.labeled_complex_candidates,full_source:fullAcceptance.data?.labeled_source_discovery_events,full_agency:fullAcceptance.data?.labeled_agency_clearance_events,coverage:fullAcceptance.data?.complex_strategy_coverage,missing:differentCommitAcceptance.data?.shadow_days,production_pass:productionAcceptance.data?.pass}));
