import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import { scheduleDueSources, completeSourceFetch, leaseVerificationJobs } from '../dist/scheduler.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare(`insert into source_registry(source_id,source_class,canonical_domain_or_account,entrypoint_url,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,market,language,currency,storage_policy,retention_policy,parser,owner) values('s1','OFFICIAL_PROMOTION','x.example','https://x.example/deals','PUBLIC_OFFICIAL_PAGE','CONDITIONAL_HTTP','ENABLED','HIGH_FOR_OWN_TERMS','2026-09-01T00:00:00Z',300000,0,'TW','zh-TW','TWD','HASH','90D','promo','airline')`).run();
raw.prepare(`insert into source_registry(source_id,source_class,canonical_domain_or_account,entrypoint_url,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,market,language,currency,storage_policy,retention_policy,parser,owner) values('s2','OFFICIAL_PROMOTION','y.example','https://y.example/deals','PUBLIC_OFFICIAL_PAGE','CONDITIONAL_HTTP','ENABLED','HIGH_FOR_OWN_TERMS','RECHECK_REQUIRED',300000,0,'TW','zh-TW','TWD','HASH','90D','promo','airline')`).run();
const a=await scheduleDueSources(db,'2026-09-15T00:00:00Z',10); const b=await scheduleDueSources(db,'2026-09-15T00:01:00Z',10); const jobs=await leaseVerificationJobs(db,'2026-09-15T00:00:01Z','worker-a',5,90); const health=await completeSourceFetch(db,{source_id:'s1',success:true,etag:'"a"',content_sha256:'a'.repeat(64)},'2026-09-15T00:00:02Z'); const c=await scheduleDueSources(db,'2026-09-15T00:10:00Z',10);
console.log(JSON.stringify({a,b,leased:jobs.length,health,c,job_count:raw.prepare('select count(*) n from verification_jobs').get().n,s2_jobs:raw.prepare("select count(*) n from verification_jobs where source_id='s2'").get().n,fetch:raw.prepare("select last_success_at,etag,content_sha256 from source_fetch_state where source_id='s1'").get(),health_row:raw.prepare("select window_start,window_end,recommended_schedule_action from source_health_windows where source_id='s1'").get()}));
