import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import worker from '../dist/worker.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}
class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){const out=[];this.x.exec('BEGIN IMMEDIATE');try{for(const s of a)out.push(await s.run());this.x.exec('COMMIT');return out}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);
raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,verification_authority,lifecycle_state,min_interval_ms,kill_switch,entrypoint_url,fetch_method,terms_snapshot_at) values('src-1','AIRLINE','https://example.com','PUBLIC_WEB','DISCOVERY_ONLY','SHADOW',60000,0,'https://example.com/deals','STATIC_HTML_DIFF','2026-09-01T00:00:00Z')").run();
raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,verification_authority,lifecycle_state,min_interval_ms,kill_switch,entrypoint_url,fetch_method,terms_snapshot_at) values('src-2','AIRLINE','https://example.org','PUBLIC_WEB','DISCOVERY_ONLY','SHADOW',60000,0,'https://example.org/deals','STATIC_HTML_DIFF','2026-09-01T00:00:00Z')").run();
raw.prepare("insert into verification_jobs(job_id,job_type,target_class,source_id,payload_json,state,available_at,created_at) values('job-1','SOURCE_FETCH','EXTERNAL_HEAVY','src-1','{\"source_id\":\"src-1\",\"url\":\"https://example.com/deals\"}','PENDING','2000-01-01T00:00:00Z','2026-09-15T00:00:00Z')").run();
const env={DB:db,WORKER_TOKEN:'worker-token-0123456789'};
async function post(path,payload,token='worker-token-0123456789'){const r=await worker.fetch(new Request('https://fare.example'+path,{method:'POST',headers:{'x-fare-worker-token':token,'content-type':'application/json'},body:JSON.stringify(payload)}),env);return {status:r.status,body:await r.json()};}
const unauthorized=await post('/verification-jobs/lease',{worker_id:'w1'},'bad');
const lease=await post('/verification-jobs/lease',{worker_id:'w1',limit:1});
const wrongWorker=await post('/ingest',{worker_id:'w2',lease_job_id:'job-1',observation_id:'obs-wrong-worker',source_id:'src-1',observed_at:'2026-09-15T00:00:00Z',canonical_url:'https://example.com/deals',content_sha256:'a'.repeat(64),privacy_class:'PUBLIC'});
const wrongSource=await post('/ingest',{worker_id:'w1',lease_job_id:'job-1',observation_id:'obs-wrong-source',source_id:'src-2',observed_at:'2026-09-15T00:00:00Z',canonical_url:'https://example.org/deals',content_sha256:'b'.repeat(64),privacy_class:'PUBLIC'});
const good=await post('/ingest',{worker_id:'w1',lease_job_id:'job-1',observation_id:'obs-good',source_id:'src-1',observed_at:'2026-09-15T00:00:00Z',canonical_url:'https://example.com/deals',content_sha256:'c'.repeat(64),privacy_class:'PUBLIC'});
const wrongComplete=await post('/verification-jobs/complete',{job_id:'job-1',worker_id:'w2',source_id:'src-1',success:true});
const complete=await post('/verification-jobs/complete',{job_id:'job-1',worker_id:'w1',source_id:'src-1',success:true});
const afterDone=await post('/ingest',{worker_id:'w1',lease_job_id:'job-1',observation_id:'obs-after',source_id:'src-1',observed_at:'2026-09-15T00:00:00Z',canonical_url:'https://example.com/deals',content_sha256:'d'.repeat(64),privacy_class:'PUBLIC'});
console.log(JSON.stringify({unauthorized:unauthorized.status,leased:lease.body.jobs?.length??0,wrong_worker:wrongWorker.status,wrong_source:wrongSource.status,good:good.status,wrong_complete:wrongComplete.status,complete:complete.status,after_done:afterDone.status,observations:raw.prepare('select count(*) n from source_observations').get().n,job_state:raw.prepare("select state from verification_jobs where job_id='job-1'").get().state}));
