import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { ingestAgencyOffer } from '../dist/partner_ingest.js';
import { projectDomainEvents } from '../dist/ingest.js';
import { leaseAgencyRechecks, completeAgencyRecheck } from '../dist/agency_recheck.js';
import { leaseAgencyCheckouts, completeAgencyCheckout } from '../dist/agency_checkout.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new DB(raw);
for(const id of ['a1','a2']){const src=`src-${id}`;raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch) values(?, 'PARTNER_PUSH',?,'PARTNER_CONTRACT','WEBHOOK','SHADOW','MEDIUM','2026-09-15T00:00:00Z',300000,0)").run(src,`${id}.example`);raw.prepare("insert into agency_partner_registry(agency_id,source_id,status,verified_business,terms_snapshot_at) values(?,?,'ENABLED',1,'2026-09-15T00:00:00Z')").run(id,src);}
const offer={agency_offer_id:'ao-checkout',agency_id:'a1',source_id:'src-a1',observation_id:'obs-checkout',product_id:'pkg-checkout',allotment_type:'CLEARANCE',origin:'TPE',destination:'OKA',departure_at:'2026-09-20T08:00:00+08:00',return_at:'2026-09-23T12:00:00+09:00',price:6999,currency:'TWD',tax_inclusion:'INCLUDED',baggage:'20KG',seats_total:2,seats_available:2,inventory_hint:'LIMITED',booking_deadline:'2026-09-16T18:00:00+08:00',ticketing_deadline:'2026-09-16T20:00:00+08:00',refund_change_terms:'NONREFUNDABLE',booking_or_contact_channel:'https://a1.example/book',observed_at:'2026-09-15T00:00:00Z',content_sha256:'a'.repeat(64),canonical_url:'https://a1.example/deal/pkg-checkout'};
await ingestAgencyOffer(db,offer,'2026-09-15T00:00:01Z'); await projectDomainEvents(db,'2026-09-15T00:00:02Z','projector',2);
const sellerLease=await leaseAgencyRechecks(db,{agency_id:'a1',worker_id:'seller-w'},'2026-09-15T01:00:00Z');
await completeAgencyRecheck(db,{recheck_id:'seller-r',queue_id:sellerLease[0].queue_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'seller-w',readback_basis:'PARTNER_API',source_url:'https://a1.example/api/pkg-checkout',content_sha256:'b'.repeat(64),observed_at:'2026-09-15T01:00:10Z',price:6888,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00'},'2026-09-15T01:00:11Z');
const none=await leaseAgencyCheckouts(db,{agency_id:'a2',worker_id:'checkout-a2'},'2026-09-15T01:01:00Z');
let leased=await leaseAgencyCheckouts(db,{agency_id:'a1',worker_id:'checkout-w'},'2026-09-15T01:01:00Z');
let wrongWorker='';try{await completeAgencyCheckout(db,{checkout_id:'co-wrong',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'wrong',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://a1.example/checkout/pkg-checkout',content_sha256:'c'.repeat(64),observed_at:'2026-09-15T01:01:10Z',final_price:6888,currency:'TWD',seats_available:1,total_includes_taxes:true,total_includes_mandatory_fees:true},'2026-09-15T01:01:11Z')}catch(e){wrongWorker=e.message}
let wrongDomain='';try{await completeAgencyCheckout(db,{checkout_id:'co-domain',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'checkout-w',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://evil.example/checkout/pkg-checkout',content_sha256:'d'.repeat(64),observed_at:'2026-09-15T01:01:10Z',final_price:6888,currency:'TWD',seats_available:1,total_includes_taxes:true,total_includes_mandatory_fees:true},'2026-09-15T01:01:11Z')}catch(e){wrongDomain=e.message}
let paymentBlocked='';try{await completeAgencyCheckout(db,{checkout_id:'co-pay',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'checkout-w',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://a1.example/checkout/pkg-checkout',content_sha256:'d'.repeat(64),observed_at:'2026-09-15T01:01:10Z',final_price:6888,currency:'TWD',seats_available:1,total_includes_taxes:true,total_includes_mandatory_fees:true,payment_dispatched:true},'2026-09-15T01:01:11Z')}catch(e){paymentBlocked=e.message}
const incomplete=await completeAgencyCheckout(db,{checkout_id:'co-incomplete',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'checkout-w',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://a1.example/checkout/pkg-checkout',content_sha256:'e'.repeat(64),observed_at:'2026-09-15T01:01:12Z',final_price:6888,currency:'TWD',seats_available:1,total_includes_taxes:true,total_includes_mandatory_fees:false},'2026-09-15T01:01:13Z');
leased=await leaseAgencyCheckouts(db,{agency_id:'a1',worker_id:'checkout-w2'},'2026-09-15T01:02:00Z');
const ok=await completeAgencyCheckout(db,{checkout_id:'co-ok',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'checkout-w2',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://a1.example/checkout/pkg-checkout',content_sha256:'f'.repeat(64),observed_at:'2026-09-15T01:02:10Z',final_price:7018,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00',total_includes_taxes:true,total_includes_mandatory_fees:true},'2026-09-15T01:02:11Z');
const idem=await completeAgencyCheckout(db,{checkout_id:'co-ok',job_id:leased[0].job_id,agency_offer_id:'ao-checkout',agency_id:'a1',worker_id:'checkout-w2',readback_basis:'PARTNER_PORTAL_CHECKOUT',checkout_url:'https://a1.example/checkout/pkg-checkout',content_sha256:'f'.repeat(64),observed_at:'2026-09-15T01:02:10Z',final_price:7018,currency:'TWD',seats_available:1,booking_deadline:'2026-09-16T18:00:00+08:00',total_includes_taxes:true,total_includes_mandatory_fees:true},'2026-09-15T01:02:12Z');
const row=raw.prepare("select seller_verification_state,price,seats_available,state from agency_inventory_offers where agency_offer_id='ao-checkout'").get();
const job=raw.prepare("select state,attempts,claimed_by,last_error from agency_checkout_jobs where agency_offer_id='ao-checkout'").get();
const ev=raw.prepare("select result_state,total_includes_taxes,total_includes_mandatory_fees,payment_dispatched from agency_checkout_evidence where checkout_id='co-ok'").get();
const intent=raw.prepare("select payload_json from candidate_alert_intents where intent_id='agency-checkout:ao-checkout:co-ok'").get();
console.log(JSON.stringify({none:none.length,firstLease:1,wrongWorker,wrongDomain,paymentBlocked,incomplete,ok,idem,row,job,ev,payload:JSON.parse(intent.payload_json),intents:raw.prepare("select count(*) n from candidate_alert_intents where intent_id='agency-checkout:ao-checkout:co-ok'").get().n}));
