import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs';
import { upsertPaymentProfile, enqueueCheckoutReprice, ingestPricingQuote } from '../dist/checkout_pricing.js';
import { ingestOfferSnapshot } from '../dist/offers.js'; import { recordProviderRuntimeReadback } from '../dist/provider_runtime.js'; import { leaseProviderJobs } from '../dist/provider_jobs.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of stmts)out.push(await s.run());this.db.exec('COMMIT');return out}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); raw.exec(fs.readFileSync(new URL('../generated/seed.generated.sql',import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare("update provider_access_registry set terms_snapshot_at='2026-09-15T00:00:00Z' where provider_id='duffel'").run();
const structure={slices:[{segments:[{segment_id:'seg1',origin:'TPE',destination:'KIX',departing_at:'2026-11-03T01:00:00Z',arriving_at:'2026-11-03T03:00:00Z',passengers:[{passenger_id:'p1',baggages:[]}]}]}],available_services:[{id:'ase1',type:'baggage',total_currency:'TWD',total_amount:'900.00',segment_ids:['seg1'],passenger_ids:['p1'],maximum_quantity:1}],price_scope:'FLIGHT_TOTAL_INCLUDES_TAX_EXCLUDES_SERVICES'};
await ingestOfferSnapshot(db,{provider_offer_id:'off1',query_fingerprint:'q1',provider:'duffel',currency:'TWD',passenger_mix:'[{"type":"adult"}]',baggage_query:'{"checked_bags_by_slice":[1],"checked_bag_kg":20}',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-09-15T01:00:00Z',raw_sha256:'a'.repeat(64),source_snapshot_id:'job-search',offer_total:5000,fare_freshness:'REFRESHED_LIVE',cached_or_live:'LIVE',offer_structure:structure});
await upsertPaymentProfile(db,{payment_profile_id:'pay1',provider_id:'duffel',payment_method_class:'CARD',credential_binding:'DUFFEL_PAYMENT_CARD_ID',enabled:true,expires_at:'2026-09-15T00:20:00Z'},'2026-09-15T00:01:00Z');
const enq=await enqueueCheckoutReprice(db,{provider_id:'duffel',provider_offer_id:'off1',payment_profile_id:'pay1',selected_services:[{id:'ase1',quantity:1}]},'2026-09-15T00:02:00Z');
await recordProviderRuntimeReadback(db,{provider_id:'duffel',worker_id:'w1',connector_version:'duffel-v2-2',credentials_present:true,capabilities:['LIVE_REPRICE','CHECKOUT_REPRICE'],ttl_seconds:300},'2026-09-15T00:02:01Z');
const jobs=await leaseProviderJobs(db,{provider_id:'duffel',worker_id:'w1',verification_types:['CHECKOUT_REPRICE'],limit:3},'2026-09-15T00:02:02Z');
const payload=JSON.parse(jobs[0].payload_json);
const quote=await ingestPricingQuote(db,{quote_id:'price:off1:q1',provider_offer_id:'off1',provider_id:'duffel',source_job_id:jobs[0].job_id,payment_profile_id:'pay1',selected_services:[{id:'ase1',quantity:1}],payment_method_class:'CARD',currency:'TWD',fare_and_services_total:5900,surcharge_total:100,grand_total:6000,priced_at:'2026-09-15T00:02:03Z',expires_at:'2026-09-15T00:20:00Z',raw_sha256:'b'.repeat(64),price_scope:'CHECKOUT_TOTAL_WITH_SELECTED_SERVICES_AND_PAYMENT_SURCHARGE'});
let badService='NONE';try{await enqueueCheckoutReprice(db,{provider_id:'duffel',provider_offer_id:'off1',payment_profile_id:'pay1',selected_services:[{id:'missing',quantity:1}]},'2026-09-15T00:03:00Z')}catch(e){badService=e.message}
console.log(JSON.stringify({enq,jobs:jobs.map(x=>({job_id:x.job_id,job_type:x.job_type,provider_mode:x.provider_mode})),payload,quote,badService,stored:raw.prepare("select provider_offer_id,currency,fare_and_services_total,surcharge_total,grand_total,price_scope from provider_pricing_quotes where quote_id='price:off1:q1'").get(),leaksCard:JSON.stringify(payload).includes('card_')||JSON.stringify(payload).includes('tcd_')}));
