import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import { cleanupExpiredNonces } from '../dist/auth.js';
import { planDueCandidateSearches, dispatchProviderSearchPlans } from '../dist/search_planner.js';
import { evaluateDueProvisionals } from '../dist/provisional.js';
class S{constructor(s,c){this.s=s;this.c=c;this.a=[]}bind(...a){this.a=a;return this}async run(){this.c.n++;return{success:true,meta:this.s.run(...this.a)}}async first(){this.c.n++;return this.s.get(...this.a)??null}async all(){this.c.n++;return{results:this.s.all(...this.a)}}}
class D{constructor(x,c){this.x=x;this.c=c}prepare(q){return new S(this.x.prepare(q),this.c)}async batch(a){this.x.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of a)out.push(await s.run());this.x.exec('COMMIT');return out}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const counter={n:0},db=new D(raw,counter);
const now='2026-09-15T03:45:00Z';
raw.prepare("insert into provider_access_registry(provider_id,access_basis,terms_snapshot_at,rate_policy,look_to_book_budget,kill_switch_state,owner) values('p1','OFFICIAL_API','2026-09-15T00:00:00Z','TARGETED_ONLY',1000,'CLEAR','test')").run();
raw.prepare("insert into runtime_profiles(profile_id,home_airports_json,checked_bag_pattern,baggage_kg,seat_required,red_eye_ok,self_transfer_ok,overnight_transfer_ok,airport_change_ok,mainland_permit_status,korea_entry_profile,foreign_origin_ok,positioning_cost_attribution,max_positioning_cost_twd,value_of_time_twd_per_hour,min_savings_for_self_transfer_twd,currency,created_at,updated_at) values('prof','[\"TPE\"]','NONE',0,0,1,1,1,1,'UNKNOWN','UNKNOWN',1,'FULL',10000,300,2000,'TWD',?,?)").run(now,now);
raw.prepare("insert into search_campaigns(campaign_id,profile_id,provider_id,origin_airports_json,destination_airports_json,departure_dates_json,trip_lengths_json,passengers_json,max_queries_per_signal,enabled,expires_at,created_at,updated_at) values('camp','prof','p1','[\"TPE\"]','[\"KIX\"]','[\"2026-11-03\"]','[3]','[{\"type\":\"adult\"}]',2,1,'2026-12-31T00:00:00Z',?,?)").run(now,now);
raw.prepare("insert into source_registry(source_id,source_class,canonical_domain_or_account,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,discovery_trust,kill_switch_state) values('s','SOCIAL','example.test','PUBLIC','PUSH','ENABLED','DISCOVERY','2026-09-15T00:00:00Z',300000,0,'HIGH','CLEAR')").run();
raw.prepare("insert into source_observations(observation_id,source_id,observed_at,content_sha256,access_basis,privacy_class) values('obs','s','2026-09-14T00:00:00Z',?,'PUBLIC','PUBLIC')").run('a'.repeat(64));
const structure=JSON.stringify({slices:[{segments:[{origin:'TPE',destination:'KIX',departing_at:'2026-11-03T01:00:00Z',arriving_at:'2026-11-03T03:30:00Z'}]}]});
function offer(id,amount,observed){raw.prepare("insert into offer_snapshots(provider_offer_id,query_fingerprint,provider,currency,baggage_query,observed_at,expires_at,raw_sha256,offer_total,fare_freshness,cached_or_live,offer_structure_json) values(?,?,'p1','TWD',?,?,'2026-10-01T00:00:00Z',?,?, 'REFRESHED_LIVE','LIVE',?)").run(id,`q-${id}`,'{"checked_bags_by_slice":[0],"checked_bag_kg":0,"seat_required":false}',observed,String(amount).padStart(64,'0').slice(-64),amount,structure)}
for(const [i,a] of [7000,6800,7200,6900,7100].entries())offer(`h${i}`,a,`2026-09-${String(8+i).padStart(2,'0')}T00:00:00Z`);offer('current',4000,'2026-09-14T00:00:00Z');
const key='k';const dims=['TPE-KIX','TPE_METRO-OSA_METRO','TPE-KIX','ONEWAY','NONSTOP','PROVIDER_OFFER','UNKNOWN','bags:0|kg:0|seat:0',2,'MONTH_11','UNKNOWN','D30_59','p1','TWD'];
for(const [id,amount,obs] of [['h0',7000,'2026-09-08T00:00:00Z'],['h1',6800,'2026-09-09T00:00:00Z'],['h2',7200,'2026-09-10T00:00:00Z'],['h3',6900,'2026-09-11T00:00:00Z'],['h4',7100,'2026-09-12T00:00:00Z'],['current',4000,'2026-09-14T00:00:00Z']])raw.prepare("insert into fare_baseline_observations(baseline_id,provider_offer_id,baseline_key,route_key,metro_pair,direction,trip_type,nonstop_or_stop,protected_or_self_transfer,fare_brand,baggage_profile,weekday,season,holiday_bucket,advance_purchase_bucket,provider,currency,amount,departure_date,observed_at,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`b-${id}`,id,key,...dims,amount,'2026-11-03',obs,now);
raw.prepare("insert into itinerary_candidates(itinerary_id,profile_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values('itin','prof','S00_DIRECT_RT',4000,0,'LOW','PROBABLE',?)").run(now);
raw.prepare("insert into candidate_plan_intakes(intake_id,itinerary_id,payload_sha256,observed_at,discovery_evidence_json) values('intake','itin',?,?,?)").run('b'.repeat(64),now,'["obs"]');
raw.prepare("insert into cost_components(cost_id,itinerary_id,type,amount,currency,twd_amount,inclusion_state,source_offer_id,dedupe_key,certainty,paid_state,refundable,observed_at) values('c','itin','FLIGHT',4000,'TWD',4000,'INCLUDED_IN_OFFER','current','flight','CONFIRMED','UNPAID',0,?)").run(now);
counter.n=0;await cleanupExpiredNonces(db,now);const planned=await planDueCandidateSearches(db,now,8,4);const dispatched=await dispatchProviderSearchPlans(db,now,2);const provisional=await evaluateDueProvisionals(db,now,1);console.log(JSON.stringify({queries:counter.n,planned,dispatched,provisional,intents:raw.prepare('select count(*) n from candidate_alert_intents').get().n}));
