import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import { ingestAgencyOffer, ingestEmailEvidence } from '../dist/partner_ingest.js'; import { projectDomainEvents } from '../dist/ingest.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
for(const [id,basis] of [['agency-src','PARTNER_CONTRACT'],['email-src','AUTHORIZED_EMAIL']]) raw.prepare(`insert into source_registry(source_id,source_class,canonical_domain_or_account,entrypoint_url,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,market,language,currency,storage_policy,retention_policy,parser,owner) values(?,?,?,?,?,'WEBHOOK','SHADOW','MEDIUM','2026-09-01T00:00:00Z',300000,0,'TW','zh-TW','TWD','HASH','90D','structured','partner')`).run(id,'PARTNER_PUSH',id+'.example','https://'+id+'.example',basis);
raw.prepare("insert into agency_partner_registry(agency_id,source_id,status,verified_business,terms_snapshot_at) values('a1','agency-src','ENABLED',1,'2026-09-01T00:00:00Z')").run();
const offer={agency_offer_id:'ao1',agency_id:'a1',source_id:'agency-src',observation_id:'obs-a1',product_id:'p1',allotment_type:'CLEARANCE',origin:'TPE',destination:'OKA',departure_at:'2026-09-20T08:00:00+08:00',return_at:'2026-09-23T12:00:00+09:00',price:6999,currency:'TWD',tax_inclusion:'INCLUDED',baggage:'20KG',seats_total:2,seats_available:2,inventory_hint:'LIMITED',booking_deadline:'2026-09-16T18:00:00+08:00',refund_change_terms:'NONREFUNDABLE',booking_or_contact_channel:'https://agency-src.example/book',observed_at:'2026-09-15T00:00:00Z',content_sha256:'a'.repeat(64),canonical_url:'https://agency-src.example/deal/p1'};
const ar=await ingestAgencyOffer(db,offer,'2026-09-15T00:00:01Z'); offer.seats_available=1; await ingestAgencyOffer(db,offer,'2026-09-15T00:10:00Z');
const email={message_id:'m1',source_id:'email-src',observation_id:'obs-e1',from_address:'promo@email-src.example',from_domain:'email-src.example',received_at:'2026-09-15T01:00:00Z',subject:'TPE-KIX sale',body_sha256:'b'.repeat(64),attachment_sha256:[],dkim_result:'PASS',spf_result:'PASS',dmarc_result:'PASS',canonical_links:['https://email-src.example/deal'],expanded_links:['https://email-src.example/deal'],link_risk_class:'LOW',retention_until:'2026-12-15T00:00:00Z'};
const er=await ingestEmailEvidence(db,email,'2026-09-15T01:00:01Z'); const forged=await ingestEmailEvidence(db,{...email,message_id:'m2',observation_id:'obs-e2',body_sha256:'c'.repeat(64),dkim_result:'FAIL',dmarc_result:'FAIL'},'2026-09-15T01:01:00Z');
let rawBlocked=false; try{await ingestEmailEvidence(db,{...email,message_id:'m3',observation_id:'obs-e3',body_sha256:'d'.repeat(64),raw_body:'secret'},'2026-09-15T01:02:00Z')}catch(e){rawBlocked=String(e).includes('RAW_EMAIL_BODY_FORBIDDEN')}
const projected=await projectDomainEvents(db,'2026-09-15T01:05:00Z','email-projector',10);
const projectedAgain=await projectDomainEvents(db,'2026-09-15T01:06:00Z','email-projector',10);
console.log(JSON.stringify({ar,er,forged,rawBlocked,projected,projectedAgain,agency:raw.prepare("select state,seats_available from agency_inventory_offers where agency_offer_id='ao1'").get(),email_count:raw.prepare('select count(*) n from email_evidence').get().n,obs_count:raw.prepare('select count(*) n from source_observations').get().n,outbox_count:raw.prepare('select count(*) n from domain_outbox').get().n,domain_done:raw.prepare("select count(*) n from domain_outbox where state='DONE'").get().n,promotion_count:raw.prepare('select count(*) n from promotion_events').get().n,promotion_state:raw.prepare('select state from promotion_events limit 1').get()?.state??null,promotion_evidence:raw.prepare("select observation_id from promotion_event_evidence limit 1").get()?.observation_id??null,priority_count:raw.prepare('select count(*) n from candidate_priority_queue').get().n,priority_types:raw.prepare('select signal_type,required_verification,priority_score,state from candidate_priority_queue order by signal_type').all(),raw_column_exists:raw.prepare("select count(*) n from pragma_table_info('email_evidence') where name in ('raw_body','body')").get().n}));
