import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import { recordAuditEvidence, recordSourceDiscoveryEdge } from '../dist/audit.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare(`insert into source_registry(source_id,source_class,canonical_domain_or_account,entrypoint_url,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,market,language,currency,storage_policy,retention_policy,parser,owner,status) values('s1','OFFICIAL_ROUTE_DIRECTORY','x.example','https://x.example','PUBLIC_OFFICIAL_PAGE','CONDITIONAL_HTTP','SHADOW','HIGH_FOR_OWN_TERMS','2026-09-01T00:00:00Z',300000,0,'TW','zh-TW','TWD','HASH','90D','route','airport','SHADOW')`).run();
const ev={evidence_id:'ev1',gate_id:'PG25',spec_version:'1.3',commit_sha:'abc',test_report_hash:'a'.repeat(64),provider_readback:{ok:true},unresolved_items:[],created_at:'2026-09-15T00:00:00Z'};
const a=await recordAuditEvidence(db,ev); const b=await recordAuditEvidence(db,ev); let conflict=false; try{await recordAuditEvidence(db,{...ev,test_report_hash:'b'.repeat(64)})}catch(e){conflict=String(e).includes('AUDIT_EVIDENCE_CONFLICT')}
const edge={from_source_id:'s1',to_candidate_source_key:'new-airport-source',relation_type:'ROUTE_DISCOVERY',observed_at:'2026-09-15T00:00:00Z',evidence_id:'obs1',confidence:0.8,onboarding_state:'DISCOVERED'}; await recordSourceDiscoveryEdge(db,edge); await recordSourceDiscoveryEdge(db,edge);
console.log(JSON.stringify({a,b,conflict,audit:raw.prepare('select count(*) n from audit_evidence').get().n,edge:raw.prepare('select count(*) n from source_discovery_edges').get().n}));
