import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import { ingestSourceObservation, projectDomainEvents } from '../dist/ingest.js';
class Stmt { constructor(s){this.s=s;this.args=[]} bind(...v){this.args=v;return this} async run(){return {success:true,meta:this.s.run(...this.args)}} async first(){return this.s.get(...this.args)??null} async all(){return {results:this.s.all(...this.args)}} }
class DB { constructor(db){this.db=db} prepare(sql){return new Stmt(this.db.prepare(sql))} async batch(stmts){this.db.exec('BEGIN IMMEDIATE');try{const o=[];for(const s of stmts)o.push(await s.run());this.db.exec('COMMIT');return o}catch(e){this.db.exec('ROLLBACK');throw e}} }
const raw=new DatabaseSync(':memory:'); for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort()) raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8')); const db=new DB(raw);
raw.prepare(`insert into source_registry(source_id,source_class,canonical_domain_or_account,entrypoint_url,access_basis,fetch_method,lifecycle_state,verification_authority,terms_snapshot_at,min_interval_ms,kill_switch,market,language,currency,storage_policy,retention_policy,parser,owner) values('s1','OFFICIAL_PROMOTION','x.example','https://x.example/deals','PUBLIC_OFFICIAL_PAGE','CONDITIONAL_HTTP','ENABLED','HIGH_FOR_OWN_TERMS','2026-09-01T00:00:00Z',300000,0,'TW','zh-TW','TWD','HASH','90D','promo','airline')`).run();
const promo={observation_id:'obs1',source_id:'s1',observed_at:'2026-09-15T00:00:00Z',canonical_url:'https://x.example/deals',content_sha256:'a'.repeat(64),parser_version:'1',privacy_class:'PUBLIC',extraction_type:'PROMOTION_SIGNAL',structured_payload:{market:'TW',airline:'IT',routes:['TPE-KIX'],prices:[{currency:'TWD',amount:3999}],promo_code:'SALE'}};
await ingestSourceObservation(db,promo,'2026-09-15T00:00:01Z'); await ingestSourceObservation(db,promo,'2026-09-15T00:00:02Z'); const pr=await projectDomainEvents(db,'2026-09-15T00:00:03Z','cron',2);
const route={observation_id:'obs2',source_id:'s1',observed_at:'2026-09-15T00:10:00Z',canonical_url:'https://x.example/routes',content_sha256:'b'.repeat(64),parser_version:'1',privacy_class:'PUBLIC',extraction_type:'ROUTE_UNIVERSE',structured_payload:{routes:['KHH-KMQ']}};
await ingestSourceObservation(db,route,'2026-09-15T00:10:01Z'); await projectDomainEvents(db,'2026-09-15T00:10:02Z','cron',2);
let privateBlocked=false; try{await ingestSourceObservation(db,{...promo,observation_id:'obs3',privacy_class:'PRIVATE_NOTIFICATION'},'2026-09-15T00:20:00Z')}catch(e){privateBlocked=String(e).includes('PRIVATE_STRUCTURED_PAYLOAD_FORBIDDEN')}
console.log(JSON.stringify({projected:pr,promotions:raw.prepare('select count(*) n from promotion_events').get().n,evidence:raw.prepare('select count(*) n from promotion_event_evidence').get().n,pstate:raw.prepare('select state from promotion_events').get().state,priority_count:raw.prepare("select count(*) n from candidate_priority_queue where signal_type='PROMOTION'").get().n,priority:raw.prepare("select required_verification,priority_score,state from candidate_priority_queue where signal_type='PROMOTION'").get(),routes:raw.prepare('select count(*) n from route_universe').get().n,route_state:raw.prepare('select state from route_universe').get().state,route_entries:raw.prepare('select count(*) n from route_universe_entries').get().n,route_entry_status:raw.prepare('select status from route_universe_entries').get().status,domain:raw.prepare('select count(*) n from domain_outbox').get().n,privateBlocked}));
