import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import { ingestConnectionBufferPolicy,evaluateTransferBoundary } from '../dist/transfer_runtime.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){this.x.exec('BEGIN');try{const o=[];for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);
await ingestConnectionBufferPolicy(db,{policy_id:'icn-low',airport:'ICN',airport_base_buffer:90,immigration_margin:60,baggage_reclaim_margin:45,terminal_transfer_margin:30,checkin_cutoff_margin:45,security_margin:30,delay_margin:60,buffer_confidence:'LOW',authority:'SYNTHETIC_OFFICIAL_MINIMUM_PLUS_MARGIN',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-10-15T00:00:00Z',raw_sha256:'a'.repeat(64)},'2026-09-15T00:00:00Z');
function itin(id,mins,{doc=true,bag=true,airportChange=false}={}){raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values(?, 'S09_KR_SELF_TRANSFER',NULL,0,'HIGH','PROBABLE','2026-09-15T00:00:00Z')").run(id);for(const t of ['a','b'])raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,segments_json) values(?,?,?,'SYN','ONE_WAY','SEPARATE_UNPROTECTED','[]')").run(`${id}-${t}`,id,`${id}-${t}`);raw.prepare("insert into transfer_boundaries(boundary_id,itinerary_id,from_ticket_id,to_ticket_id,airport,self_transfer,protection_type,mct_status,requires_entry,requires_bag_reclaim,through_bag_status,terminal_change,airport_change,scheduled_buffer_minutes,required_buffer_minutes,buffer_confidence,evidence_id) values(?,?,?,?, 'ICN',1,'SEPARATE_UNPROTECTED',NULL,1,1,'NO',1,?,?,0,'LOW','transfer-evidence')").run(`b-${id}`,id,`${id}-a`,`${id}-b`,airportChange?1:0,mins);for(const [type,ok] of [['DOCUMENT_CLEAR',doc],['BAGGAGE_FEASIBLE',bag]])raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values(?,?,?,'SYN','2026-09-15T00:00:00Z','2026-09-15T01:00:00Z','SYN','e')").run(id,type,ok?'PASS':'FAIL');}
itin('short',300);const short=await evaluateTransferBoundary(db,'b-short','2026-09-15T00:01:00Z');
itin('ok',400);const ok=await evaluateTransferBoundary(db,'b-ok','2026-09-15T00:01:00Z');
itin('nodoc',400,{doc:false});const nodoc=await evaluateTransferBoundary(db,'b-nodoc','2026-09-15T00:01:00Z');
itin('airport',500,{airportChange:true});const airport=await evaluateTransferBoundary(db,'b-airport','2026-09-15T00:01:00Z');
raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values('stale','S09_KR_SELF_TRANSFER',NULL,0,'HIGH','PROBABLE','2026-09-15T00:00:00Z')").run();for(const t of ['a','b'])raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,segments_json) values(?,?,?,'SYN','ONE_WAY','SEPARATE_UNPROTECTED','[]')").run(`stale-${t}`,'stale',`stale-${t}`);raw.prepare("insert into transfer_boundaries(boundary_id,itinerary_id,from_ticket_id,to_ticket_id,airport,self_transfer,protection_type,requires_entry,requires_bag_reclaim,terminal_change,airport_change,scheduled_buffer_minutes,required_buffer_minutes,buffer_confidence,evidence_id) values('b-stale','stale','stale-a','stale-b','PUS',1,'SEPARATE_UNPROTECTED',0,0,0,0,400,0,'LOW','e')").run();const stale=await evaluateTransferBoundary(db,'b-stale','2026-09-15T00:01:00Z');
console.log(JSON.stringify({short,ok,nodoc,airport,stale,okFacet:raw.prepare("select status,reason_code from readiness_facets where itinerary_id='ok' and facet_type='CONNECTION_ACCEPTABLE'").get()}));
