import { DatabaseSync } from 'node:sqlite'; import fs from 'node:fs'; import worker from '../dist/worker.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){const o=[];this.x.exec('BEGIN');try{for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);const secret='s';
function itin(id,state='CONFIRMED',fresh=true,cost=1){raw.prepare("insert into itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values(?, 'S00_DIRECT_RT',5000,?,'LOW',?,'2026-09-15T00:00:00Z')").run(id,cost,state);for(const t of ['FARE_VERIFIED','DOCUMENT_CLEAR','CONNECTION_ACCEPTABLE','BAGGAGE_FEASIBLE','COST_COMPLETE','COUPON_SEQUENCE_CLEAR','POLICY_FRESH'])raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values(?,?,'PASS','OK','2026-09-15T00:00:00Z',?,'TEST','e')").run(id,t,fresh?'2099-01-01T00:00:00Z':'2000-01-01T00:00:00Z');}
itin('good');itin('stale','CONFIRMED',false);itin('prob','PROBABLE',true);itin('nocost','CONFIRMED',true,0);
const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);
async function post(obj){const body=JSON.stringify(obj);const ts=String(Date.now());const sb=await crypto.subtle.sign('HMAC',key,enc.encode(`${ts}.${body}`));const sig=[...new Uint8Array(sb)].map(x=>x.toString(16).padStart(2,'0')).join('');const r=await worker.fetch(new Request('https://x/candidate/evaluate',{method:'POST',headers:{'x-fare-timestamp':ts,'x-fare-signature':sig},body}),{DB:db,INGEST_HMAC_SECRET:secret});return {status:r.status,body:await r.json()};}
const good=await post({intent_id:'i-good',itinerary_id:'good',payload:{x:1}});const stale=await post({intent_id:'i-stale',itinerary_id:'stale',payload:{x:1}});const prob=await post({intent_id:'i-prob',itinerary_id:'prob',payload:{x:1}});const nocost=await post({intent_id:'i-nocost',itinerary_id:'nocost',payload:{x:1}});const forged=await post({intent_id:'i-forged',itinerary_id:'prob',payload:{x:1},actionable:true});const provisional=await post({intent_id:'i-prov',itinerary_id:'prob',payload:{x:1},provisional_trigger:true});const admin=await post({intent_id:'i-admin',itinerary_id:'good',alert_class:'ADMIN',payload:{x:1}});
console.log(JSON.stringify({good,stale,prob,nocost,forged,provisional,admin,intents:raw.prepare('select count(*) n from candidate_alert_intents').get().n}));
