import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import { ingestConnectionBufferPolicy,ingestAirportChangePolicy,evaluateTransferBoundary } from '../dist/transfer_runtime.js';
import { upsertRuntimeProfile } from '../dist/profile.js';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async run(){return{success:true,meta:this.s.run(...this.a)}}async first(){return this.s.get(...this.a)??null}async all(){return{results:this.s.all(...this.a)}}}
class D{constructor(x){this.x=x}prepare(q){return new S(this.x.prepare(q))}async batch(a){const o=[];this.x.exec('BEGIN');try{for(const s of a)o.push(await s.run());this.x.exec('COMMIT');return o}catch(e){this.x.exec('ROLLBACK');throw e}}}
const raw=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(fs.readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8'));const db=new D(raw);
for(const airport of ['ICN','GMP'])await ingestConnectionBufferPolicy(db,{policy_id:`${airport.toLowerCase()}-low`,airport,airport_base_buffer:90,immigration_margin:60,baggage_reclaim_margin:45,terminal_transfer_margin:30,checkin_cutoff_margin:45,security_margin:30,delay_margin:60,buffer_confidence:'LOW',authority:'SYNTHETIC_OFFICIAL_MINIMUM_PLUS_MARGIN',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-10-15T00:00:00Z',raw_sha256:(airport==='ICN'?'a':'b').repeat(64)},'2026-09-15T00:00:00Z');
await ingestAirportChangePolicy(db,{policy_id:'icn-gmp-ground',from_airport:'ICN',to_airport:'GMP',ground_transfer_minutes:75,ground_contingency_minutes:30,authority:'SYNTHETIC_AIRPORT_GROUND_MODEL',observed_at:'2026-09-15T00:00:00Z',expires_at:'2026-10-15T00:00:00Z',raw_sha256:'c'.repeat(64)},'2026-09-15T00:00:00Z');
async function profile(id,{self=true,overnight=true,airport=true}={}){await upsertRuntimeProfile(db,{profile_id:id,home_city:'Synthetic',home_airports:['TPE'],checked_bag_pattern:'BOTH',baggage_kg:20,seat_required:false,red_eye_ok:true,self_transfer_ok:self,overnight_transfer_ok:overnight,airport_change_ok:airport,mainland_permit_status:'VALID',korea_entry_profile:'CHECK_AT_QUERY_TIME',foreign_origin_ok:true,positioning_cost_attribution:'FULL',max_positioning_cost_twd:3000,value_of_time_twd_per_hour:300,min_savings_for_self_transfer_twd:2000,currency:'TWD'},'2026-09-15T00:00:00Z');}
await profile('p-ok');await profile('p-no-self',{self:false});await profile('p-no-overnight',{overnight:false});await profile('p-no-airport',{airport:false});
function itin(id,mins,{doc=true,bag=true,profileId='p-ok',airportChange=false,arrival=null,departure=null,overnight=false,terminalChange=true}={}){raw.prepare("insert into itinerary_candidates(itinerary_id,profile_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values(?,?,'S09_KR_SELF_TRANSFER',NULL,0,'HIGH','PROBABLE','2026-09-15T00:00:00Z')").run(id,profileId);for(const t of ['a','b'])raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,segments_json) values(?,?,?,'SYN','ONE_WAY','SEPARATE_UNPROTECTED','[]')").run(`${id}-${t}`,id,`${id}-${t}`);raw.prepare("insert into transfer_boundaries(boundary_id,itinerary_id,from_ticket_id,to_ticket_id,airport,arrival_airport,departure_airport,self_transfer,protection_type,mct_status,requires_entry,requires_bag_reclaim,through_bag_status,terminal_change,airport_change,overnight_transfer,scheduled_buffer_minutes,required_buffer_minutes,buffer_confidence,evidence_id) values(?,?,?,?, ?,?,?,1,'SEPARATE_UNPROTECTED',NULL,1,1,'NO',?,?,?,?,0,'LOW','transfer-evidence')").run(`b-${id}`,id,`${id}-a`,`${id}-b`,departure??'ICN',arrival,departure,terminalChange?1:0,airportChange?1:0,overnight?1:0,mins);for(const [type,ok] of [['DOCUMENT_CLEAR',doc],['BAGGAGE_FEASIBLE',bag]])raw.prepare("insert into readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) values(?,?,?,'SYN','2026-09-15T00:00:00Z','2026-09-15T01:00:00Z','SYN','e')").run(id,type,ok?'PASS':'FAIL');}
itin('short',300);const short=await evaluateTransferBoundary(db,'b-short','2026-09-15T00:01:00Z');
itin('ok',400);const ok=await evaluateTransferBoundary(db,'b-ok','2026-09-15T00:01:00Z');
itin('nodoc',400,{doc:false});const nodoc=await evaluateTransferBoundary(db,'b-nodoc','2026-09-15T00:01:00Z');
itin('noself',400,{profileId:'p-no-self'});const noself=await evaluateTransferBoundary(db,'b-noself','2026-09-15T00:01:00Z');
itin('overnight',600,{profileId:'p-no-overnight',overnight:true});const overnight=await evaluateTransferBoundary(db,'b-overnight','2026-09-15T00:01:00Z');
itin('airport-disallowed',600,{profileId:'p-no-airport',airportChange:true,arrival:'ICN',departure:'GMP',terminalChange:false});const airportDisallowed=await evaluateTransferBoundary(db,'b-airport-disallowed','2026-09-15T00:01:00Z');
itin('airport-ok',500,{airportChange:true,arrival:'ICN',departure:'GMP',terminalChange:false});const airportOk=await evaluateTransferBoundary(db,'b-airport-ok','2026-09-15T00:01:00Z');
itin('airport-missing',500,{airportChange:true,departure:'GMP',terminalChange:false});const airportMissing=await evaluateTransferBoundary(db,'b-airport-missing','2026-09-15T00:01:00Z');
raw.prepare("insert into itinerary_candidates(itinerary_id,profile_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_class,verification_state,updated_at) values('stale','p-ok','S09_KR_SELF_TRANSFER',NULL,0,'HIGH','PROBABLE','2026-09-15T00:00:00Z')").run();for(const t of ['a','b'])raw.prepare("insert into ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,segments_json) values(?,?,?,'SYN','ONE_WAY','SEPARATE_UNPROTECTED','[]')").run(`stale-${t}`,'stale',`stale-${t}`);raw.prepare("insert into transfer_boundaries(boundary_id,itinerary_id,from_ticket_id,to_ticket_id,airport,self_transfer,protection_type,requires_entry,requires_bag_reclaim,terminal_change,airport_change,scheduled_buffer_minutes,required_buffer_minutes,buffer_confidence,evidence_id) values('b-stale','stale','stale-a','stale-b','PUS',1,'SEPARATE_UNPROTECTED',0,0,0,0,400,0,'LOW','e')").run();const stale=await evaluateTransferBoundary(db,'b-stale','2026-09-15T00:01:00Z');
console.log(JSON.stringify({short,ok,nodoc,noself,overnight,airportDisallowed,airportOk,airportMissing,stale,okFacet:raw.prepare("select status,reason_code from readiness_facets where itinerary_id='ok' and facet_type='CONNECTION_ACCEPTABLE'").get()}));
