import type { D1Database } from "./types.js";
import { ackCandidateSignal } from "./priority.js";
import { enqueueAlertIntent } from "./outbox.js";
import { enqueueAgencyCheckoutJob } from "./agency_checkout.js";
import { assertAgencyUrlAllowed } from "./agency_security.js";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
function sha(v:string){return /^[a-f0-9]{64}$/i.test(v);}
function terms(v:string|null|undefined){return !!v&&v!=="RECHECK_REQUIRED"&&Number.isFinite(Date.parse(v));}
function after(nowIso:string,seconds:number){return new Date(Date.parse(nowIso)+seconds*1000).toISOString();}
async function partnerReady(db:D1Database,agencyId:string){const a=await db.prepare("SELECT agency_id,source_id,status,verified_business,terms_snapshot_at FROM agency_partner_registry WHERE agency_id=?").bind(agencyId).first<any>();return a&&a.status==="ENABLED"&&Number(a.verified_business)===1&&terms(a.terms_snapshot_at)?a:null;}
export async function leaseAgencyRechecks(db:D1Database,input:{agency_id:string;worker_id:string;limit?:number},nowIso:string){
  assert(!!input.agency_id&&!!input.worker_id,"AGENCY_RECHECK_IDENTITY_REQUIRED");const partner=await partnerReady(db,input.agency_id);assert(!!partner,"AGENCY_PARTNER_NOT_ENABLED");
  await db.prepare(`UPDATE candidate_priority_queue SET state='PENDING',claimed_by=NULL,lease_until=NULL WHERE state='LEASED' AND lease_until IS NOT NULL AND lease_until<=? AND signal_type='AGENCY_CLEARANCE' AND signal_id IN (SELECT agency_offer_id FROM agency_inventory_offers WHERE agency_id=?)`).bind(nowIso,input.agency_id).run();
  const until=after(nowIso,90),limit=Math.min(Math.max(Number(input.limit??5),1),5);
  return (await db.prepare(`UPDATE candidate_priority_queue SET state='LEASED',claimed_by=?,lease_until=?,attempts=attempts+1
    WHERE queue_id IN (SELECT q.queue_id FROM candidate_priority_queue q JOIN agency_inventory_offers a ON a.agency_offer_id=q.signal_id WHERE q.state='PENDING' AND q.available_at<=? AND q.signal_type='AGENCY_CLEARANCE' AND q.required_verification='SELLER_RECHECK' AND a.agency_id=? AND a.state NOT IN ('EXPIRED','SOLD_OUT') AND (a.seats_available IS NULL OR a.seats_available>0) AND (a.booking_deadline IS NULL OR datetime(a.booking_deadline)>datetime(?)) AND (a.payment_deadline IS NULL OR datetime(a.payment_deadline)>datetime(?)) AND (a.ticketing_deadline IS NULL OR datetime(a.ticketing_deadline)>datetime(?)) ORDER BY q.priority_score DESC,q.first_observed_at ASC LIMIT ?)
    AND state='PENDING' RETURNING queue_id,signal_id,priority_score,price_claim_json,source_evidence_id,attempts,lease_until`).bind(input.worker_id,until,nowIso,input.agency_id,nowIso,nowIso,nowIso,limit).all<any>()).results;
}
export interface AgencyRecheckInput {recheck_id:string;queue_id:string;agency_offer_id:string;agency_id:string;worker_id:string;readback_basis:"PARTNER_API"|"PARTNER_PORTAL"|"OFFICIAL_PRODUCT_PAGE";source_url:string;content_sha256:string;observed_at:string;price:number;currency:string;seats_available?:number|null;booking_deadline?:string|null;payment_deadline?:string|null;ticketing_deadline?:string|null;anonymous_payment?:boolean;}
export async function completeAgencyRecheck(db:D1Database,input:AgencyRecheckInput,nowIso:string){
  assert(!!input.recheck_id&&!!input.queue_id&&!!input.agency_offer_id&&!!input.agency_id&&!!input.worker_id,"AGENCY_RECHECK_IDENTITY_REQUIRED");assert(["PARTNER_API","PARTNER_PORTAL","OFFICIAL_PRODUCT_PAGE"].includes(input.readback_basis),"AGENCY_RECHECK_BASIS_INVALID");assert(input.source_url.startsWith("https://")&&sha(input.content_sha256),"AGENCY_RECHECK_EVIDENCE_INVALID");assert(Number.isFinite(Date.parse(input.observed_at))&&Date.parse(input.observed_at)<=Date.parse(nowIso),"AGENCY_RECHECK_TIME_INVALID");assert(Number.isFinite(input.price)&&input.price>=0&&/^[A-Z]{3}$/.test(input.currency),"AGENCY_RECHECK_PRICE_INVALID");if(input.seats_available!=null)assert(Number.isInteger(input.seats_available)&&input.seats_available>=0,"AGENCY_RECHECK_SEATS_INVALID");
  const existing=await db.prepare("SELECT queue_id,agency_offer_id,agency_id,worker_id,content_sha256,result_state FROM agency_recheck_evidence WHERE recheck_id=?").bind(input.recheck_id).first<any>();if(existing){if(existing.queue_id!==input.queue_id||existing.agency_offer_id!==input.agency_offer_id||existing.agency_id!==input.agency_id||existing.worker_id!==input.worker_id||existing.content_sha256!==input.content_sha256)throw new Error("AGENCY_RECHECK_IMMUTABLE_CONFLICT");return {state:existing.result_state,idempotent:true};}
  const partner=await partnerReady(db,input.agency_id);assert(!!partner,"AGENCY_PARTNER_NOT_ENABLED");
  const row=await db.prepare(`SELECT q.state,q.claimed_by,q.lease_until,q.signal_id,a.currency,a.tax_inclusion,a.baggage,a.product_id,a.booking_or_contact_channel,a.booking_deadline,a.payment_deadline,a.ticketing_deadline FROM candidate_priority_queue q JOIN agency_inventory_offers a ON a.agency_offer_id=q.signal_id WHERE q.queue_id=? AND q.signal_type='AGENCY_CLEARANCE' AND q.required_verification='SELLER_RECHECK' AND a.agency_id=?`).bind(input.queue_id,input.agency_id).first<any>();
  assert(!!row&&row.signal_id===input.agency_offer_id&&row.state==="LEASED"&&row.claimed_by===input.worker_id&&row.lease_until&&Date.parse(row.lease_until)>Date.parse(nowIso),"AGENCY_RECHECK_LIVE_LEASE_REQUIRED");
  await assertAgencyUrlAllowed(db,input.agency_id,input.source_url,row.booking_or_contact_channel);
  let result:"SELLER_CONFIRMED"|"SOLD_OUT"|"RECHECK_REQUIRED"="SELLER_CONFIRMED",retryable=false,error:string|null=null;
  const deadlines=[input.booking_deadline??row.booking_deadline,input.payment_deadline??row.payment_deadline,input.ticketing_deadline??row.ticketing_deadline].filter((x:any)=>x&&Number.isFinite(Date.parse(x)));
  if(deadlines.some((x:any)=>Date.parse(x)<=Date.parse(nowIso))){result="RECHECK_REQUIRED";error="AGENCY_RECHECK_DEADLINE_PASSED";}
  if(input.currency!==row.currency){result="RECHECK_REQUIRED";retryable=true;error="AGENCY_RECHECK_CURRENCY_MISMATCH";}else if(input.anonymous_payment){result="RECHECK_REQUIRED";retryable=true;error="AGENCY_ANONYMOUS_PAYMENT_BLOCKED";}else if(input.seats_available===0){result="SOLD_OUT";}
  await db.prepare("INSERT INTO agency_recheck_evidence(recheck_id,queue_id,agency_offer_id,agency_id,worker_id,readback_basis,source_url,content_sha256,observed_at,price,currency,seats_available,booking_deadline,payment_deadline,ticketing_deadline,result_state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")
    .bind(input.recheck_id,input.queue_id,input.agency_offer_id,input.agency_id,input.worker_id,input.readback_basis,input.source_url,input.content_sha256,input.observed_at,input.price,input.currency,input.seats_available??null,input.booking_deadline??null,input.payment_deadline??null,input.ticketing_deadline??null,result,nowIso).run();
  if(result==="RECHECK_REQUIRED"){const state=await ackCandidateSignal(db,{queue_id:input.queue_id,worker_id:input.worker_id,ok:false,retryable,error},nowIso);return {state,result,retryable:true,idempotent:false};}
  if(result==="SOLD_OUT"){await db.prepare("UPDATE agency_inventory_offers SET seats_available=0,observed_at=?,state='SOLD_OUT' WHERE agency_offer_id=?").bind(input.observed_at,input.agency_offer_id).run();const state=await ackCandidateSignal(db,{queue_id:input.queue_id,worker_id:input.worker_id,ok:true},nowIso);return {state,result,idempotent:false};}
  await db.prepare("UPDATE agency_inventory_offers SET seller_verification_state='VERIFIED_READBACK',price=?,seats_available=COALESCE(?,seats_available),booking_deadline=COALESCE(?,booking_deadline),payment_deadline=COALESCE(?,payment_deadline),ticketing_deadline=COALESCE(?,ticketing_deadline),observed_at=?,state='SELLER_CONFIRMED' WHERE agency_offer_id=?").bind(input.price,input.seats_available??null,input.booking_deadline??null,input.payment_deadline??null,input.ticketing_deadline??null,input.observed_at,input.agency_offer_id).run();
  const state=await ackCandidateSignal(db,{queue_id:input.queue_id,worker_id:input.worker_id,ok:true},nowIso);
  await enqueueAgencyCheckoutJob(db,input.agency_offer_id,input.agency_id,nowIso);
  const payload={kind:"P0-PROVISIONAL",verification_state:"SELLER_CONFIRMED",actionable:false,bookable:false,subject_type:"AGENCY_CLEARANCE",agency_offer_id:input.agency_offer_id,agency_id:input.agency_id,product_id:row.product_id,price:input.price,currency:input.currency,tax_inclusion:row.tax_inclusion,baggage:row.baggage,seats_available:input.seats_available??null,booking_deadline:input.booking_deadline??null,booking_channel:row.booking_or_contact_channel,recheck_evidence_id:input.recheck_id,readback_basis:input.readback_basis};
  await enqueueAlertIntent(db,{intent_id:`agency-provisional:${input.agency_offer_id}:${input.recheck_id}`,itinerary_id:`agency:${input.agency_offer_id}`,alert_class:"DEAL",payload},nowIso);return {state,result,idempotent:false};
}
