import { actionable, cashTripCost, selfTransferAcceptable, couponSequenceClear, protectionClassification, canConfirmFromEvidence } from "./core.js";
import { validateCandidatePlan } from "./intake.js";
import { verifyMultiProvider, amadeusCanConfirm } from "./verification.js";
import { policyUsable } from "./policy.js";
import { provenanceValid, promotionFingerprint, promoEligible, clearanceState, emailTrust, dispatchAllowed, adaptiveSchedule, routeUniverseDiff, socialRetention, extractPromotionText } from "./source.js";
import { ACTIVE_STRATEGIES, boundedExpand, boundedStrategySearch, foreignOriginCycleCost, priceBeatEligible } from "./strategy.js";
import { complexAlertCard } from "./alerts.js";
import { quotaDegrade, win11State, burstDecision, workerBudget } from "./capacity.js";
import { onboardingCandidates } from "./discovery.js";
import { evaluateShadow, evaluateComplexReview } from "./shadow.js";
import { applyCorrection } from "./corrections.js";
const input=JSON.parse(process.argv[3]??"null");
let out:unknown;
switch(process.argv[2]){
  case "actionable": out=actionable(input.verification_state,input.facets,new Date(input.at));break;
  case "cash": out=cashTripCost(input.offer_total_twd,input.components);break;
  case "validate-plan": out=validateCandidatePlan(input);break;
  case "self-transfer": out=selfTransferAcceptable(input);break;
  case "coupon-sequence": out=couponSequenceClear(input);break;
  case "protection": out=protectionClassification(input);break;
  case "can-confirm": out=canConfirmFromEvidence(input);break;
  case "multi-provider": out=verifyMultiProvider(input.evidence,input.now,input.tolerance);break;
  case "amadeus-can-confirm": out=amadeusCanConfirm(input);break;
  case "policy-usable": out=policyUsable(input.policy,input.event_at,input.now);break;
  case "provenance-valid": out=provenanceValid(input);break;
  case "promo-fingerprint": out=promotionFingerprint(input);break;
  case "promo-eligible": out=promoEligible(input.promo,input.query);break;
  case "clearance-state": out=clearanceState(input);break;
  case "email-trust": out=emailTrust(input);break;
  case "dispatch-allowed": out=dispatchAllowed(input.policy,input.now);break;
  case "adaptive-schedule": out=adaptiveSchedule(input);break;
  case "route-diff": out=routeUniverseDiff(input.before,input.after);break;
  case "social-retention": out=socialRetention(input);break;
  case "extract-promo-text": out=extractPromotionText(input.text,input.market);break;
  case "strategies": out=ACTIVE_STRATEGIES;break;
  case "bounded-expand": out=boundedExpand(input.items,input.maxTickets);break;
  case "strategy-search": out=boundedStrategySearch(input.items,input.options);break;
  case "foreign-cycle-cost": out=foreignOriginCycleCost(input);break;
  case "price-beat": out=priceBeatEligible(input);break;
  case "complex-alert": out=complexAlertCard(input);break;
  case "quota-degrade": out=quotaDegrade(input);break;
  case "win11-state": out=win11State(input);break;
  case "burst-decision": out=burstDecision(input);break;
  case "onboarding": out=onboardingCandidates(input);break;
  case "worker-budget": out=workerBudget(input);break;
  case "shadow-acceptance": out=evaluateShadow(input);break;
  case "shadow-complex-review": out=evaluateComplexReview(input);break;
  case "apply-correction": out=applyCorrection(input.history,input.event);break;
  default: throw new Error("UNKNOWN_COMMAND");
}
console.log(JSON.stringify(out));
