import type { D1Database } from "./types.js";

function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
function sha(v:string){return /^[a-f0-9]{64}$/i.test(v);}
function isFresh(v:string|null|undefined,nowIso:string){return !!v&&Number.isFinite(Date.parse(v))&&Date.parse(v)>Date.parse(nowIso);}
export interface FxSnapshotInput {fx_snapshot_id:string;base_currency:string;quote_currency:string;rate:number;rate_source:string;rate_observed_at:string;provider_spread:number;card_fx_fee:number;settlement_currency:string;expires_at:string;raw_sha256:string;}
export async function ingestFxSnapshot(db:D1Database,x:FxSnapshotInput){
  assert(!!x.fx_snapshot_id&&/^[A-Z]{3}$/.test(x.base_currency)&&/^[A-Z]{3}$/.test(x.quote_currency),"FX_IDENTITY_INVALID");assert(Number.isFinite(x.rate)&&x.rate>0,"FX_RATE_INVALID");assert(Number.isFinite(x.provider_spread)&&x.provider_spread>=0&&x.provider_spread<=1,"FX_SPREAD_INVALID");assert(Number.isFinite(x.card_fx_fee)&&x.card_fx_fee>=0&&x.card_fx_fee<=1,"FX_FEE_INVALID");assert(Number.isFinite(Date.parse(x.rate_observed_at))&&Number.isFinite(Date.parse(x.expires_at))&&Date.parse(x.expires_at)>Date.parse(x.rate_observed_at),"FX_TIME_INVALID");assert(sha(x.raw_sha256),"FX_HASH_INVALID");
  const prior=await db.prepare("SELECT raw_sha256 FROM fx_snapshots WHERE fx_snapshot_id=?").bind(x.fx_snapshot_id).first<any>();if(prior){if(prior.raw_sha256!==x.raw_sha256)throw new Error("FX_SNAPSHOT_ID_CONFLICT");return {fx_snapshot_id:x.fx_snapshot_id,idempotent:true};}
  await db.prepare("INSERT INTO fx_snapshots(fx_snapshot_id,base_currency,quote_currency,rate,rate_source,rate_observed_at,provider_spread,card_fx_fee,settlement_currency,expires_at,raw_sha256) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(x.fx_snapshot_id,x.base_currency,x.quote_currency,x.rate,x.rate_source,x.rate_observed_at,x.provider_spread,x.card_fx_fee,x.settlement_currency,x.expires_at,x.raw_sha256).run();return {fx_snapshot_id:x.fx_snapshot_id,idempotent:false};
}
async function twdFromFx(db:D1Database,currency:string,amount:number,fxId:string|null|undefined,nowIso:string){
  if(currency==="TWD")return {twd:amount,fx:null as string|null,expires:null as string|null};assert(!!fxId,"FX_REQUIRED");const x=await db.prepare("SELECT base_currency,quote_currency,rate,provider_spread,card_fx_fee,expires_at FROM fx_snapshots WHERE fx_snapshot_id=?").bind(fxId).first<any>();assert(!!x&&x.base_currency===currency&&x.quote_currency==="TWD","FX_PAIR_MISMATCH");assert(isFresh(x.expires_at,nowIso),"FX_STALE");return {twd:amount*Number(x.rate)*(1+Number(x.provider_spread)+Number(x.card_fx_fee)),fx:fxId,expires:x.expires_at};
}
export async function upsertMandatoryCostEvidence(db:D1Database,input:{cost_id:string;itinerary_id:string;type:string;amount:number;currency:string;dedupe_key:string;source_evidence_id:string;certainty:string;observed_at:string;evidence_expires_at:string;fx_snapshot_id?:string|null;refundable?:boolean},nowIso:string){
  assert(!!input.cost_id&&!!input.itinerary_id&&!!input.type&&!!input.dedupe_key&&!!input.source_evidence_id,"COST_EVIDENCE_IDENTITY_REQUIRED");assert(Number.isFinite(input.amount)&&input.amount>=0,"COST_EVIDENCE_AMOUNT_INVALID");assert(/^[A-Z]{3}$/.test(input.currency),"COST_EVIDENCE_CURRENCY_INVALID");assert(isFresh(input.evidence_expires_at,nowIso),"COST_EVIDENCE_STALE");const itin=await db.prepare("SELECT itinerary_id FROM itinerary_candidates WHERE itinerary_id=?").bind(input.itinerary_id).first();assert(!!itin,"ITINERARY_NOT_FOUND");const fx=await twdFromFx(db,input.currency,input.amount,input.fx_snapshot_id,nowIso);
  await db.prepare(`INSERT INTO cost_components(cost_id,itinerary_id,type,amount,currency,twd_amount,inclusion_state,source_offer_id,policy_evidence_id,source_evidence_id,dedupe_key,certainty,effective_event_at,paid_state,refundable,fx_snapshot_id,observed_at,evidence_expires_at)
    VALUES(?,?,?,?,?,?,'ADD_ON',NULL,NULL,?,?,?,?, 'UNPAID',?,?,?,?) ON CONFLICT(cost_id) DO UPDATE SET amount=excluded.amount,currency=excluded.currency,twd_amount=excluded.twd_amount,source_evidence_id=excluded.source_evidence_id,dedupe_key=excluded.dedupe_key,certainty=excluded.certainty,effective_event_at=excluded.effective_event_at,refundable=excluded.refundable,fx_snapshot_id=excluded.fx_snapshot_id,observed_at=excluded.observed_at,evidence_expires_at=excluded.evidence_expires_at`)
    .bind(input.cost_id,input.itinerary_id,input.type,input.amount,input.currency,fx.twd,input.source_evidence_id,input.dedupe_key,input.certainty,input.observed_at,input.refundable?1:0,fx.fx,input.observed_at,input.evidence_expires_at).run();
  return {cost_id:input.cost_id,twd_amount:fx.twd};
}
export async function attachFxToCost(db:D1Database,input:{cost_id:string;fx_snapshot_id:string},nowIso:string){
  const c=await db.prepare("SELECT cost_id,currency,amount FROM cost_components WHERE cost_id=?").bind(input.cost_id).first<any>();assert(!!c,"COST_NOT_FOUND");const fx=await twdFromFx(db,c.currency,Number(c.amount),input.fx_snapshot_id,nowIso);await db.prepare("UPDATE cost_components SET twd_amount=?,fx_snapshot_id=? WHERE cost_id=?").bind(fx.twd,fx.fx,input.cost_id).run();return {cost_id:input.cost_id,twd_amount:fx.twd};
}
async function failCost(db:D1Database,itineraryId:string,reason:string,nowIso:string){const exp=new Date(Date.parse(nowIso)+15*60000).toISOString();await db.batch([db.prepare("UPDATE itinerary_candidates SET cash_trip_cost_twd=NULL,cost_complete=0,updated_at=? WHERE itinerary_id=?").bind(nowIso,itineraryId),db.prepare("INSERT INTO readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) VALUES(?,'COST_COMPLETE','FAIL',?,?,?,'COST_ENGINE',?) ON CONFLICT(itinerary_id,facet_type) DO UPDATE SET status=excluded.status,reason_code=excluded.reason_code,observed_at=excluded.observed_at,expires_at=excluded.expires_at,authority=excluded.authority,evidence_id=excluded.evidence_id").bind(itineraryId,reason,nowIso,exp,`cost:${itineraryId}:${reason}`)]);return {cost_complete:false,reason};}
export async function recomputeDirectAllInCost(db:D1Database,itineraryId:string,nowIso:string){
  const itin=await db.prepare("SELECT itinerary_id,profile_id,strategy_type FROM itinerary_candidates WHERE itinerary_id=?").bind(itineraryId).first<any>();if(!itin)return failCost(db,itineraryId,"ITINERARY_NOT_FOUND",nowIso);if(!["S00_DIRECT_RT","S01_DIRECT_OW"].includes(itin.strategy_type))return failCost(db,itineraryId,"DIRECT_COST_ENGINE_NOT_APPLICABLE",nowIso);if(!itin.profile_id)return failCost(db,itineraryId,"PROFILE_LINEAGE_MISSING",nowIso);
  const profile=await db.prepare("SELECT seat_required FROM runtime_profiles WHERE profile_id=?").bind(itin.profile_id).first<any>();if(!profile)return failCost(db,itineraryId,"PROFILE_LINEAGE_MISSING",nowIso);
  const baggage=await db.prepare("SELECT status,expires_at FROM readiness_facets WHERE itinerary_id=? AND facet_type='BAGGAGE_FEASIBLE'").bind(itineraryId).first<any>();if(!baggage||baggage.status!=="PASS"||!isFresh(baggage.expires_at,nowIso))return failCost(db,itineraryId,"BAGGAGE_COST_OR_ALLOWANCE_INCOMPLETE",nowIso);
  const costs=(await db.prepare("SELECT cost_id,type,amount,currency,twd_amount,inclusion_state,dedupe_key,fx_snapshot_id,evidence_expires_at,pricing_quote_id FROM cost_components WHERE itinerary_id=?").bind(itineraryId).all<any>()).results;
  const base=costs.find(c=>c.dedupe_key==="offer-total"&&c.type==="CHECKOUT_TOTAL"&&c.pricing_quote_id);if(!base||base.twd_amount==null)return failCost(db,itineraryId,base?"CHECKOUT_FX_INCOMPLETE":"CHECKOUT_PRICE_REQUIRED",nowIso);
  const q=await db.prepare("SELECT expires_at FROM provider_pricing_quotes WHERE quote_id=?").bind(base.pricing_quote_id).first<any>();if(!q||!isFresh(q.expires_at,nowIso))return failCost(db,itineraryId,"CHECKOUT_PRICE_STALE",nowIso);
  const required=["GROUND_ORIGIN","GROUND_DESTINATION"];if(profile.seat_required)required.push("SEAT_SELECTION");for(const type of required){const c=costs.find(x=>x.type===type&&x.inclusion_state!=="UNKNOWN");if(!c||c.twd_amount==null)return failCost(db,itineraryId,`${type}_COST_REQUIRED`,nowIso);if(c.evidence_expires_at&&!isFresh(c.evidence_expires_at,nowIso))return failCost(db,itineraryId,`${type}_COST_STALE`,nowIso);}
  for(const c of costs){if(c.inclusion_state==="UNKNOWN")return failCost(db,itineraryId,"UNKNOWN_COST_COMPONENT",nowIso);if(c.currency!=="TWD"){if(!c.fx_snapshot_id)return failCost(db,itineraryId,"FX_REQUIRED",nowIso);const fx=await db.prepare("SELECT expires_at FROM fx_snapshots WHERE fx_snapshot_id=?").bind(c.fx_snapshot_id).first<any>();if(!fx||!isFresh(fx.expires_at,nowIso))return failCost(db,itineraryId,"FX_STALE",nowIso);}}
  let total=Number(base.twd_amount);const seen=new Set<string>([base.dedupe_key]);for(const c of costs){if(c.inclusion_state!=="ADD_ON"||seen.has(c.dedupe_key))continue;seen.add(c.dedupe_key);if(c.twd_amount==null)return failCost(db,itineraryId,"ADD_ON_TWD_COST_MISSING",nowIso);total+=Number(c.twd_amount);}
  const expiries=[q.expires_at,baggage.expires_at,...costs.map(c=>c.evidence_expires_at).filter(Boolean)].map(Date.parse).filter(Number.isFinite);const expiry=new Date(Math.min(...expiries)).toISOString();await db.batch([db.prepare("UPDATE itinerary_candidates SET cash_trip_cost_twd=?,cost_complete=1,updated_at=? WHERE itinerary_id=?").bind(total,nowIso,itineraryId),db.prepare("INSERT INTO readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) VALUES(?,'COST_COMPLETE','PASS','DIRECT_ALL_IN_COST_COMPLETE',?,?, 'COST_ENGINE',?) ON CONFLICT(itinerary_id,facet_type) DO UPDATE SET status=excluded.status,reason_code=excluded.reason_code,observed_at=excluded.observed_at,expires_at=excluded.expires_at,authority=excluded.authority,evidence_id=excluded.evidence_id").bind(itineraryId,nowIso,expiry,`cost:${itineraryId}:complete`)]);return {cost_complete:true,cash_trip_cost_twd:total,expires_at:expiry};
}
