import type { CandidatePlanInput, D1Database, D1PreparedStatement } from "./types.js";
import { REQUIRED_FACETS } from "./types.js";
import { validateScenarioCost } from "./core.js";

const MAX_BATCH_STATEMENTS = 48;
const MAX_TICKETS = 8, MAX_TRANSFERS = 8, MAX_COSTS = 16, MAX_DOCUMENTS = 8, MAX_LIABILITIES = 8;

function assert(cond:boolean, msg:string): asserts cond { if (!cond) throw new Error(msg); }
function nonempty(v:string, name:string){ assert(typeof v === "string" && v.trim().length > 0, `${name}_REQUIRED`); }
function finite(v:number, name:string){ assert(Number.isFinite(v), `${name}_INVALID`); }
async function sha256Hex(text:string){ const b=await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join(""); }

export function validateCandidatePlan(p:CandidatePlanInput){
  nonempty(p.intake_id,"INTAKE_ID"); nonempty(p.itinerary.itinerary_id,"ITINERARY_ID"); nonempty(p.itinerary.strategy_type,"STRATEGY_TYPE");
  assert(validateScenarioCost(p.itinerary.scenario_cost_twd), "SCENARIO_COST_ORDER_INVALID");
  assert(p.tickets.length > 0 && p.tickets.length <= MAX_TICKETS, "TICKET_COUNT_INVALID");
  assert(p.transfers.length <= MAX_TRANSFERS, "TRANSFER_COUNT_INVALID"); assert(p.costs.length <= MAX_COSTS, "COST_COUNT_INVALID");
  assert(p.documents.length <= MAX_DOCUMENTS, "DOCUMENT_COUNT_INVALID"); assert(p.four_leg_liabilities.length <= MAX_LIABILITIES, "LIABILITY_COUNT_INVALID");
  const facetTypes = new Set(p.readiness.map(x=>x.facet_type)); assert(facetTypes.size === p.readiness.length, "READINESS_DUPLICATE");
  assert(REQUIRED_FACETS.every(x=>facetTypes.has(x)), "READINESS_INCOMPLETE");
  const ticketIds = new Set(p.tickets.map(x=>x.ticket_id)); assert(ticketIds.size === p.tickets.length, "TICKET_ID_DUPLICATE");
  for (const t of p.tickets){ nonempty(t.ticket_id,"TICKET_ID"); nonempty(t.pnr_group,"PNR_GROUP"); assert(Array.isArray(t.segments) && t.segments.length > 0,"SEGMENTS_REQUIRED"); }
  for (const tr of p.transfers){ assert(ticketIds.has(tr.from_ticket_id) && ticketIds.has(tr.to_ticket_id),"TRANSFER_TICKET_UNKNOWN"); finite(tr.scheduled_buffer_minutes,"SCHEDULED_BUFFER"); finite(tr.required_buffer_minutes,"REQUIRED_BUFFER"); }
  const dedupe = new Set<string>(); for (const c of p.costs){ nonempty(c.cost_id,"COST_ID"); finite(c.amount,"COST_AMOUNT"); assert(!dedupe.has(c.dedupe_key),"COST_DEDUPE_DUPLICATE"); dedupe.add(c.dedupe_key); assert(!!c.source_offer_id || !!c.policy_evidence_id,"COST_EVIDENCE_REQUIRED"); }
  for (const l of p.four_leg_liabilities){ finite(l.amount,"LIABILITY_AMOUNT"); finite(l.remaining_exposure,"REMAINING_EXPOSURE"); finite(l.recoverable_amount,"RECOVERABLE_AMOUNT"); assert(l.remaining_exposure >= 0 && l.recoverable_amount >= 0,"LIABILITY_NEGATIVE"); }
  return true;
}

function stmt(db:D1Database, sql:string, ...values:unknown[]):D1PreparedStatement { return db.prepare(sql).bind(...values); }
export async function persistCandidatePlan(db:D1Database, p:CandidatePlanInput, observedAt = new Date().toISOString()){
  validateCandidatePlan(p);
  const payload = JSON.stringify(p); const payloadHash = await sha256Hex(payload);
  const offerIds=[...new Set(p.costs.map(c=>c.source_offer_id).filter((x):x is string=>!!x))];
  if(offerIds.length){const marks=offerIds.map(()=>'?').join(','); const rows=(await db.prepare(`SELECT provider_offer_id FROM offer_snapshots WHERE provider_offer_id IN (${marks})`).bind(...offerIds).all<{provider_offer_id:string}>()).results; const have=new Set(rows.map(r=>r.provider_offer_id)); const missing=offerIds.filter(x=>!have.has(x)); if(missing.length)throw new Error(`SOURCE_OFFER_NOT_FOUND:${missing.join(',')}`);}
  const prior = await db.prepare("SELECT payload_sha256 FROM candidate_plan_intakes WHERE intake_id=?").bind(p.intake_id).first<{payload_sha256:string}>();
  if (prior && prior.payload_sha256 !== payloadHash) throw new Error("IDEMPOTENCY_CONFLICT");
  const q:D1PreparedStatement[]=[];
  q.push(stmt(db,"INSERT INTO candidate_plan_intakes(intake_id,itinerary_id,payload_sha256,observed_at) VALUES(?,?,?,?) ON CONFLICT(intake_id) DO UPDATE SET payload_sha256=excluded.payload_sha256",p.intake_id,p.itinerary.itinerary_id,payloadHash,observedAt));
  const i=p.itinerary;
  q.push(stmt(db,"INSERT INTO itinerary_candidates(itinerary_id,strategy_type,cash_trip_cost_twd,cost_complete,risk_adjusted_cost_twd,scenario_cost_json,generalized_cost_twd,risk_class,verification_state,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(itinerary_id) DO UPDATE SET strategy_type=excluded.strategy_type,cash_trip_cost_twd=excluded.cash_trip_cost_twd,cost_complete=excluded.cost_complete,risk_adjusted_cost_twd=excluded.risk_adjusted_cost_twd,scenario_cost_json=excluded.scenario_cost_json,generalized_cost_twd=excluded.generalized_cost_twd,risk_class=excluded.risk_class,verification_state=excluded.verification_state,updated_at=excluded.updated_at",i.itinerary_id,i.strategy_type,i.cash_trip_cost_twd,i.cost_complete?1:0,i.risk_adjusted_cost_twd??null,i.scenario_cost_twd?JSON.stringify(i.scenario_cost_twd):null,i.generalized_cost_twd??null,i.risk_class,i.verification_state,observedAt));
  for(const t of p.tickets) q.push(stmt(db,"INSERT INTO ticket_components(ticket_id,itinerary_id,pnr_group,provider,ticket_type,connection_protection_type,validating_carrier,ticket_stock,segments_json,fare_brand,refund_rule,change_rule) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(ticket_id) DO UPDATE SET pnr_group=excluded.pnr_group,provider=excluded.provider,ticket_type=excluded.ticket_type,connection_protection_type=excluded.connection_protection_type,validating_carrier=excluded.validating_carrier,ticket_stock=excluded.ticket_stock,segments_json=excluded.segments_json,fare_brand=excluded.fare_brand,refund_rule=excluded.refund_rule,change_rule=excluded.change_rule",t.ticket_id,i.itinerary_id,t.pnr_group,t.provider,t.ticket_type,t.connection_protection_type,t.validating_carrier??null,t.ticket_stock??null,JSON.stringify(t.segments),t.fare_brand??null,t.refund_rule??null,t.change_rule??null));
  for(const tr of p.transfers) q.push(stmt(db,"INSERT INTO transfer_boundaries(boundary_id,itinerary_id,from_ticket_id,to_ticket_id,airport,self_transfer,protection_type,validating_carrier,mct_status,requires_entry,requires_bag_reclaim,through_bag_status,terminal_change,airport_change,scheduled_buffer_minutes,required_buffer_minutes,buffer_confidence,reaccommodation_basis,evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(boundary_id) DO UPDATE SET scheduled_buffer_minutes=excluded.scheduled_buffer_minutes,required_buffer_minutes=excluded.required_buffer_minutes,buffer_confidence=excluded.buffer_confidence,evidence_id=excluded.evidence_id",tr.boundary_id,i.itinerary_id,tr.from_ticket_id,tr.to_ticket_id,tr.airport,tr.self_transfer?1:0,tr.protection_type,tr.validating_carrier??null,tr.mct_status??null,tr.requires_entry?1:0,tr.requires_bag_reclaim?1:0,tr.through_bag_status??null,tr.terminal_change?1:0,tr.airport_change?1:0,tr.scheduled_buffer_minutes,tr.required_buffer_minutes,tr.buffer_confidence,tr.reaccommodation_basis??null,tr.evidence_id));
  for(const c of p.costs) q.push(stmt(db,"INSERT INTO cost_components(cost_id,itinerary_id,type,amount,currency,twd_amount,inclusion_state,source_offer_id,policy_evidence_id,dedupe_key,certainty,effective_event_at,paid_state,refundable,fx_snapshot_id,observed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(cost_id) DO UPDATE SET amount=excluded.amount,twd_amount=excluded.twd_amount,inclusion_state=excluded.inclusion_state,certainty=excluded.certainty,observed_at=excluded.observed_at",c.cost_id,i.itinerary_id,c.type,c.amount,c.currency,c.twd_amount,c.inclusion_state,c.source_offer_id??null,c.policy_evidence_id??null,c.dedupe_key,c.certainty,c.effective_event_at??null,c.paid_state,c.refundable?1:0,c.fx_snapshot_id??null,c.observed_at));
  for(const f of p.readiness) q.push(stmt(db,"INSERT INTO readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(itinerary_id,facet_type) DO UPDATE SET status=excluded.status,reason_code=excluded.reason_code,observed_at=excluded.observed_at,expires_at=excluded.expires_at,authority=excluded.authority,evidence_id=excluded.evidence_id",i.itinerary_id,f.facet_type,f.status,f.reason_code,f.observed_at,f.expires_at,f.authority,f.evidence_id));
  for(const d of p.documents) q.push(stmt(db,"INSERT INTO document_requirements(document_id,itinerary_id,jurisdiction,travel_event,traveler_document_class,status,announced_at,observed_at,effective_from,effective_to,valid_for_event_at,jurisdiction_timezone,authority_source,source_snapshot_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(document_id) DO UPDATE SET status=excluded.status,observed_at=excluded.observed_at,effective_from=excluded.effective_from,effective_to=excluded.effective_to,valid_for_event_at=excluded.valid_for_event_at,authority_source=excluded.authority_source,source_snapshot_id=excluded.source_snapshot_id",d.document_id,i.itinerary_id,d.jurisdiction,d.travel_event,d.traveler_document_class,d.status,d.announced_at??null,d.observed_at,d.effective_from??null,d.effective_to??null,d.valid_for_event_at,d.jurisdiction_timezone,d.authority_source,d.source_snapshot_id));
  for(const l of p.four_leg_liabilities) q.push(stmt(db,"INSERT INTO four_leg_liabilities(liability_id,itinerary_id,cycle_id,component_type,amount,paid_state,refundable,booking_deadline,travel_deadline,remaining_exposure,recoverable_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(liability_id) DO UPDATE SET amount=excluded.amount,paid_state=excluded.paid_state,refundable=excluded.refundable,booking_deadline=excluded.booking_deadline,travel_deadline=excluded.travel_deadline,remaining_exposure=excluded.remaining_exposure,recoverable_amount=excluded.recoverable_amount",l.liability_id,i.itinerary_id,l.cycle_id,l.component_type,l.amount,l.paid_state,l.refundable?1:0,l.booking_deadline??null,l.travel_deadline??null,l.remaining_exposure,l.recoverable_amount));
  if(q.length > MAX_BATCH_STATEMENTS) throw new Error(`D1_BATCH_BUDGET_EXCEEDED:${q.length}`);
  const result=await db.batch(q); return {intake_id:p.intake_id,itinerary_id:i.itinerary_id,payload_sha256:payloadHash,statements:q.length,result_count:result.length};
}
