import type { D1Database } from "./types.js";

function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
function fresh(v:string,now:string){return Number.isFinite(Date.parse(v))&&Date.parse(v)>Date.parse(now);}
export interface CarrierTicketingPolicyInput {policy_id:string;carrier:string;policy_type:"COUPON_SEQUENCE"|"BACK_TO_BACK";consequence:"ALLOW"|"COUPON_SEQUENCE_VOID_RISK"|"COUPON_RECALCULATION_LIABILITY"|"CARRIER_REFUSAL_RISK"|"UNKNOWN_POLICY_CONSEQUENCE"|"BACK_TO_BACK_RESTRICTED";terms_url:string;article_or_clause:string;observed_at:string;expires_at:string;source_snapshot_hash:string;status:"CURRENT"|"RECHECK_REQUIRED"|"STALE";}
export async function ingestCarrierTicketingPolicy(db:D1Database,p:CarrierTicketingPolicyInput,nowIso:string){
  for(const k of ["policy_id","carrier","policy_type","consequence","terms_url","article_or_clause","observed_at","expires_at","source_snapshot_hash","status"] as const)assert(!!p[k],"TICKETING_POLICY_FIELD_REQUIRED");
  assert(/^https:\/\//.test(p.terms_url),"TICKETING_POLICY_URL_INVALID");assert(/^[a-f0-9]{64}$/i.test(p.source_snapshot_hash),"TICKETING_POLICY_HASH_INVALID");assert(Number.isFinite(Date.parse(p.observed_at))&&Number.isFinite(Date.parse(p.expires_at))&&Date.parse(p.expires_at)>Date.parse(p.observed_at),"TICKETING_POLICY_TIME_INVALID");
  const prior=await db.prepare("SELECT source_snapshot_hash FROM carrier_ticketing_policies WHERE policy_id=?").bind(p.policy_id).first<any>();if(prior){if(prior.source_snapshot_hash!==p.source_snapshot_hash)throw new Error("TICKETING_POLICY_IMMUTABLE_CONFLICT");return {policy_id:p.policy_id,idempotent:true};}
  await db.prepare("INSERT INTO carrier_ticketing_policies(policy_id,carrier,policy_type,consequence,terms_url,article_or_clause,observed_at,expires_at,source_snapshot_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(p.policy_id,p.carrier,p.policy_type,p.consequence,p.terms_url,p.article_or_clause,p.observed_at,p.expires_at,p.source_snapshot_hash,p.status,nowIso).run();return {policy_id:p.policy_id,idempotent:false};
}
function segmentTimes(raw:string){const s=JSON.parse(raw);assert(Array.isArray(s)&&s.length>0,"TICKET_SEGMENTS_REQUIRED");const dep=s.map((x:any)=>Date.parse(x.departing_at)).filter(Number.isFinite);const arr=s.map((x:any)=>Date.parse(x.arriving_at)).filter(Number.isFinite);assert(dep.length===s.length&&arr.length===s.length,"TICKET_SEGMENT_TIME_INVALID");return {count:s.length,start:Math.min(...dep),end:Math.max(...arr),skipped:s.some((x:any)=>x.intentionally_skipped===true)};}
function nestedOrCrossing(a:{start:number;end:number},b:{start:number;end:number}){return (a.start<b.start&&b.start<a.end&&a.end<=b.end)||(a.start<=b.start&&b.end<=a.end)||(b.start<=a.start&&a.end<=b.end)||(b.start<a.start&&a.start<b.end&&b.end<=a.end);}
async function currentPolicy(db:D1Database,carrier:string,type:string,nowIso:string){const p=await db.prepare("SELECT policy_id,consequence,expires_at,status FROM carrier_ticketing_policies WHERE carrier=? AND policy_type=? ORDER BY observed_at DESC LIMIT 1").bind(carrier,type).first<any>();return p&&p.status==="CURRENT"&&fresh(p.expires_at,nowIso)?p:null;}
export async function evaluateTicketingGuards(db:D1Database,itineraryId:string,nowIso:string){
  const tickets=(await db.prepare("SELECT ticket_id,provider,validating_carrier,segments_json FROM ticket_components WHERE itinerary_id=? ORDER BY ticket_id").bind(itineraryId).all<any>()).results;assert(tickets.length>0,"ITINERARY_TICKETS_NOT_FOUND");
  const parsed=tickets.map(t=>({...t,...segmentTimes(t.segments_json),carrier:String(t.validating_carrier??t.provider)}));
  const skipped=parsed.filter(t=>t.skipped);let couponStatus:"PASS"|"FAIL"="PASS",couponReason="COUPON_SEQUENCE_IN_ORDER",couponEvidence="ticket-segments";
  if(skipped.length){couponStatus="FAIL";const carriers=[...new Set(skipped.map(t=>t.carrier))];const reasons=[];const evidence=[];for(const c of carriers){const p=await currentPolicy(db,c,"COUPON_SEQUENCE",nowIso);reasons.push(p?.consequence??"UNKNOWN_POLICY_CONSEQUENCE");if(p)evidence.push(`carrier-policy:${p.policy_id}`);}couponReason=reasons.sort().join("+");couponEvidence=evidence.join(",")||"carrier-policy:MISSING";}
  const expiry=new Date(Date.parse(nowIso)+15*60000).toISOString();await db.prepare("INSERT INTO readiness_facets(itinerary_id,facet_type,status,reason_code,observed_at,expires_at,authority,evidence_id) VALUES(?,'COUPON_SEQUENCE_CLEAR',?,?,?,?, 'TICKETING_GUARD',?) ON CONFLICT(itinerary_id,facet_type) DO UPDATE SET status=excluded.status,reason_code=excluded.reason_code,observed_at=excluded.observed_at,expires_at=excluded.expires_at,authority=excluded.authority,evidence_id=excluded.evidence_id").bind(itineraryId,couponStatus,couponReason,nowIso,expiry,couponEvidence).run();
  let backToBack=false,backReason="NO_BACK_TO_BACK_PATTERN";for(let i=0;i<parsed.length;i++)for(let j=i+1;j<parsed.length;j++){const a=parsed[i],b=parsed[j];if(a.count<2||b.count<2||a.carrier!==b.carrier||!nestedOrCrossing(a,b))continue;backToBack=true;const p=await currentPolicy(db,a.carrier,"BACK_TO_BACK",nowIso);if(!p||p.consequence!=="ALLOW"){backReason=p?.consequence??"BACK_TO_BACK_POLICY_UNKNOWN";await db.prepare("UPDATE itinerary_candidates SET verification_state='NEEDS_HUMAN',updated_at=? WHERE itinerary_id=?").bind(nowIso,itineraryId).run();}}
  return {itinerary_id:itineraryId,coupon_status:couponStatus,coupon_reason:couponReason,back_to_back_detected:backToBack,back_to_back_reason:backReason};
}
